"""Generate ``refs.bib`` from ``kind='citation'`` refs in a workspace.

The chase worker mints ``kind='paper'`` refs as primary sources land
in the corpus; the planner LLM mints ``kind='citation'`` refs that
point at those papers via ``source_handle='paper:<slug>'``. To
actually produce a compiling LaTeX document we need a ``.bib`` file
the planner can ``\\cite{}`` against.

This module enumerates citations tagged with the workspace's project
(``project:<slug>``) and emits one BibTeX entry per unique source
paper. Used by:

* The workspace lazy-init (one-time empty placeholder).
* The Layer-3 compile guard at ``STATUS:done`` (regenerate before
  ``latexmk`` so the latest set is on disk).
* The chase worker when a new paper finishes ingestion (so the
  bib stays fresh between full STATUS:done cycles).

We do NOT attempt full BibTeX-format fidelity — the goal is "the
``\\cite{<slug>}`` keys the LLM uses resolve to *something*
bibtex-compatible." For papers with rich metadata (authors, year,
journal, DOI) we render those fields; minimal-metadata stubs land
as ``@misc`` entries with a note explaining the gap.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import TYPE_CHECKING, Any

from precis.utils.authors import author_display

if TYPE_CHECKING:
    from precis.store import Store

log = logging.getLogger(__name__)


def write_workspace_bib(store: Store, *, workspace_root: Path, project_tag: str) -> int:
    """Write ``refs.bib`` for the workspace; return entry count.

    Idempotent. Always overwrites ``refs.bib`` so a deleted citation
    disappears from the bib on the next regen. Empty workspace
    (no citations yet) writes a single comment line so the file
    exists for ``latexmk``.

    ``project_tag`` is the ``project:<slug>`` value the citations
    must carry to be included. The Layer-3 compile guard reads it
    from the workspace path.
    """
    citations = _load_workspace_citations(store, project_tag=project_tag)
    bib_path = workspace_root / "refs.bib"
    entries: list[str] = [
        "% Generated by precis from kind='citation' refs.",
        f"% Project: {project_tag}",
        f"% Entries: {len(citations)}",
        "",
    ]
    seen_keys: set[str] = set()
    for cit in citations:
        bib_key, entry = _render_citation(cit)
        if bib_key in seen_keys:
            continue
        seen_keys.add(bib_key)
        entries.append(entry)
        entries.append("")
    bib_path.write_text("\n".join(entries))
    return len(seen_keys)


def _load_workspace_citations(
    store: Store, *, project_tag: str
) -> list[dict[str, Any]]:
    """Return citations tagged with ``project_tag`` joined to source papers."""
    with store.pool.connection() as conn:
        rows = conn.execute(
            """
            SELECT cit.ref_id, cit.title, cit.meta,
                   COALESCE(
                     (SELECT t.value FROM ref_tags rt JOIN tags t ON t.tag_id = rt.tag_id
                       WHERE rt.ref_id = cit.ref_id AND t.namespace = 'OPEN'
                         AND t.value LIKE 'source-handle:%%' LIMIT 1
                     ),
                     ''
                   ) AS source_handle_tag,
                   src.ref_id AS source_ref_id,
                   src.title AS source_title,
                   src.slug AS source_slug,
                   src.meta AS source_meta,
                   src.authors AS source_authors,
                   src.year AS source_year
              FROM refs cit
              JOIN ref_tags rt ON rt.ref_id = cit.ref_id
              JOIN tags t ON t.tag_id = rt.tag_id
              LEFT JOIN links l ON l.src_ref_id = cit.ref_id AND l.relation = 'cites'
              LEFT JOIN refs src ON src.ref_id = l.dst_ref_id AND src.kind = 'paper'
                                AND src.deleted_at IS NULL
             WHERE cit.kind = 'citation'
               AND cit.deleted_at IS NULL
               AND t.namespace = 'OPEN'
               AND t.value = %s
             ORDER BY cit.ref_id
            """,
            (project_tag,),
        ).fetchall()
    out: list[dict[str, Any]] = []
    for r in rows:
        out.append(
            {
                "citation_id": int(r[0]),
                "claim": r[1] or "",
                "meta": r[2] or {},
                "source_handle_tag": r[3] or "",
                "paper_ref_id": int(r[4]) if r[4] else None,
                "paper_title": r[5] or "",
                "paper_slug": r[6] or "",
                "paper_meta": r[7] or {},
                "paper_authors": r[8] or [],
                "paper_year": r[9],
            }
        )
    return out


def _render_citation(cit: dict[str, Any]) -> tuple[str, str]:
    """Return ``(bib_key, full_bibtex_entry)`` for one citation."""
    bib_key = cit.get("paper_slug") or f"cit{cit['citation_id']}"
    bib_key = _safe_bib_key(bib_key)

    authors = cit.get("paper_authors") or []
    title = (cit.get("paper_title") or cit.get("claim") or "Untitled").strip()
    year = cit.get("paper_year")
    paper_meta = cit.get("paper_meta") or {}
    journal = paper_meta.get("journal") or paper_meta.get("publication") or ""
    doi = paper_meta.get("doi") or ""

    has_rich = bool(authors and year and (journal or doi))
    entry_kind = "article" if has_rich else "misc"

    fields: list[str] = []
    if authors:
        author_str = " and ".join(_author_name(a) for a in authors)
        fields.append(f"  author = {{{author_str}}}")
    fields.append(f"  title = {{{_escape_bib(title)}}}")
    if year:
        fields.append(f"  year = {{{year}}}")
    if journal:
        fields.append(f"  journal = {{{_escape_bib(journal)}}}")
    if doi:
        fields.append(f"  doi = {{{doi}}}")
    if not has_rich:
        # Honest gap marker so the missing-metadata case is visible
        # in the rendered PDF or grep'able in the .bib.
        fields.append(
            f"  note = {{Stub entry — citation ref #{cit['citation_id']}; "
            "paper metadata pending ingest}}"
        )
    body = ",\n".join(fields)
    entry = f"@{entry_kind}{{{bib_key},\n{body}\n}}"
    return bib_key, entry


def _safe_bib_key(key: str) -> str:
    """Strip characters that BibTeX rejects in citation keys."""
    out = "".join(c if (c.isalnum() or c in "-_:") else "" for c in key)
    return out or "untitled"


def _escape_bib(text: str) -> str:
    """Light escaping — keep braces balanced, escape % and &."""
    text = text.replace("\\", "\\textbackslash{}")
    text = text.replace("%", "\\%")
    text = text.replace("&", "\\&")
    text = text.replace("$", "\\$")
    text = text.replace("#", "\\#")
    return text.replace("\n", " ").strip()


def _author_name(author: Any) -> str:
    """Render one author entry in BibTeX ``Family, Given`` order.

    Tolerant of every stored shape via the canonical
    :func:`precis.utils.authors.author_display`; falls back to
    ``"Anonymous"`` for an empty / unparseable entry."""
    return author_display(author, order="sortable") or "Anonymous"


__all__ = ["write_workspace_bib"]
