"""``paper_authors`` 1NF table + the ``set_paper_authors`` write choke
point (docs/backlog/paper-authors-1nf.md §S1).

``paper_authors`` is the source of truth; ``refs.authors`` is a jsonb
*projection* regenerated by the store on every write. These tests cover
the write path (insert/update, the human-source guard), the migration's
raw-SQL backfill projection + the Python ``authors-resplit`` follow-up,
the table-backed ``author=`` search, and the drift health check.
"""

from __future__ import annotations

from precis.cli.paper import resplit_legacy_authors
from precis.health_checks import paper_authors_drift
from precis.store import Store
from precis.store.migrate import _execute_dump_sql
from tests.conftest import MIGRATIONS_DIR


def _migration_projection_sql() -> str:
    """Slice migration 0168's data-backfill INSERT out of the file, so
    the test can re-run just that block against a hand-edited row
    without replaying the whole (already-applied) migration."""
    text = (MIGRATIONS_DIR / "0168_paper_authors.sql").read_text(encoding="utf-8")
    start = text.index("INSERT INTO paper_authors")
    marker = "ON CONFLICT (ref_id, position) DO NOTHING;"
    end = text.index(marker, start) + len(marker)
    return text[start:end]


# ── write choke point ──────────────────────────────────────────────


def test_insert_ref_projects_paper_authors(store: Store) -> None:
    ref = store.insert_ref(
        kind="paper",
        slug="goldsmith-et-al",
        title="A paper with a mixed byline",
        authors=[
            {
                "given": "Bryan R.",
                "family": "Goldsmith",
                "orcid": "0000-0002-1825-0097",
            },
            {"name": "Zywucka, N."},
            {"name": "Aabid Hamid"},
        ],
    )
    rows = store.get_paper_authors(ref.id)
    assert [r["position"] for r in rows] == [1, 2, 3]
    assert rows[0]["given"] == "Bryan"
    assert rows[0]["middle"] == "R."
    assert rows[0]["family"] == "Goldsmith"
    assert rows[0]["orcid"] == "0000-0002-1825-0097"
    assert rows[1]["family"] == "Zywucka"
    assert rows[1]["given"] == "N."
    assert rows[2]["name_raw"] == "Aabid Hamid"
    assert rows[2]["given"] == ""
    assert rows[2]["family"] == ""

    # refs.authors is the regenerated projection, in lockstep with the table.
    assert isinstance(ref.authors, list)
    assert len(ref.authors) == len(rows) == 3


def test_update_paper_fields_authors_source_and_human_guard(store: Store) -> None:
    ref = store.insert_ref(
        kind="paper", slug="rewrite-me", title="T", authors=[{"name": "A One"}]
    )

    store.update_paper_fields(
        ref.id, authors=[{"given": "Bea", "family": "Two"}], authors_source="crossref"
    )
    rows = store.get_paper_authors(ref.id)
    assert [r["source"] for r in rows] == ["crossref"]
    assert rows[0]["family"] == "Two"

    # A human-facing door (default authors_source mapping via `source=`)
    # writes source='human'.
    updated = store.update_paper_fields(
        ref.id, authors=[{"given": "Cee", "family": "Three"}], source="web-edit"
    )
    rows2 = store.get_paper_authors(ref.id)
    assert rows2[0]["source"] == "human"
    assert rows2[0]["family"] == "Three"
    assert updated.authors == [{"given": "Cee", "family": "Three"}]

    # A subsequent non-human write is a no-op — the human row survives.
    store.update_paper_fields(
        ref.id, authors=[{"given": "Dee", "family": "Four"}], authors_source="crossref"
    )
    rows3 = store.get_paper_authors(ref.id)
    assert rows3 == rows2
    # ... and the jsonb is re-projected from the human rows, not left
    # holding the rejected byline update_paper_fields wrote first.
    fresh = store.get_ref(kind="paper", id=ref.id)
    assert fresh is not None
    assert fresh.authors == [{"given": "Cee", "family": "Three"}]


def test_draft_write_creates_no_paper_authors_rows(store: Store) -> None:
    ref = store.insert_ref(
        kind="draft", slug="d-authors", title="D", authors=[{"name": "Someone"}]
    )
    assert store.get_paper_authors(ref.id) == []

    store.update_paper_fields(
        ref.id, authors=[{"name": "Someone Else"}], source="web-edit"
    )
    assert store.get_paper_authors(ref.id) == []


# ── migration backfill projection + authors-resplit ────────────────


def test_migration_projection_then_resplit(store: Store) -> None:
    ref = store.insert_ref(kind="paper", slug="legacy-proj", title="T")
    with store.pool.connection() as conn:
        conn.execute(
            "UPDATE refs SET authors = %s::jsonb WHERE ref_id = %s",
            (
                '[{"name": "Zywucka, N."}, '
                '{"given": "Bryan R.", "family": "Goldsmith"}]',
                ref.id,
            ),
        )
        conn.execute("DELETE FROM paper_authors WHERE ref_id = %s", (ref.id,))
        with conn.cursor() as cur:
            _execute_dump_sql(cur, _migration_projection_sql())

    rows = store.get_paper_authors(ref.id)
    assert len(rows) == 2
    assert all(r["source"] == "legacy" for r in rows)
    zywucka = next(r for r in rows if r["family"] == "Zywucka")
    assert zywucka["given"] == "N."
    assert zywucka["middle"] == ""
    goldsmith = next(r for r in rows if r["family"] == "Goldsmith")
    assert goldsmith["given"] == "Bryan R."
    assert goldsmith["middle"] == ""

    n = resplit_legacy_authors(store)
    assert n >= 1

    rows2 = store.get_paper_authors(ref.id)
    goldsmith2 = next(r for r in rows2 if r["family"] == "Goldsmith")
    assert goldsmith2["given"] == "Bryan"
    assert goldsmith2["middle"] == "R."


def test_authors_resplit_dry_run_does_not_write(store: Store) -> None:
    ref = store.insert_ref(kind="paper", slug="legacy-dry", title="T")
    with store.pool.connection() as conn:
        conn.execute(
            "UPDATE refs SET authors = %s::jsonb WHERE ref_id = %s",
            ('[{"given": "Bryan R.", "family": "Goldsmith"}]', ref.id),
        )
        conn.execute("DELETE FROM paper_authors WHERE ref_id = %s", (ref.id,))
        with conn.cursor() as cur:
            _execute_dump_sql(cur, _migration_projection_sql())

    before = store.get_paper_authors(ref.id)
    n = resplit_legacy_authors(store, dry_run=True)
    assert n >= 1
    after = store.get_paper_authors(ref.id)
    assert before == after


# ── table-backed author= search ─────────────────────────────────────


def test_find_papers_by_author_table_backed(store: Store) -> None:
    luo = store.insert_ref(
        kind="paper",
        slug="luo-ge-paper",
        title="Canonical-byline paper",
        authors=[
            {"given": "Ronggang", "family": "Luo"},
            {"given": "Shengbo", "family": "Ge"},
        ],
    )
    hamid = store.insert_ref(
        kind="paper",
        slug="hamid-paper",
        title="Name-raw-only byline paper",
        authors=[{"name": "Aabid Hamid"}],
    )
    store.insert_ref(
        kind="paper",
        slug="other-paper",
        title="Unrelated",
        authors=[{"name": "Jane Doe"}],
    )

    assert store.find_papers_by_author(kind="paper", q="Luo") == [luo.id]
    assert store.find_papers_by_author(kind="paper", q="Ronggang Luo") == [luo.id]
    assert store.find_papers_by_author(kind="paper", q="Luo, Ronggang") == [luo.id]
    assert store.find_papers_by_author(kind="paper", q="Aabid Hamid") == [hamid.id]

    # full_name collapses the empty middle: a middle='' row still matches
    # the single-spaced "Given Family" substring, and a split-middle row
    # matches with its initial in place.
    store.update_paper_fields(
        luo.id,
        authors=[{"given": "Ronggang X.", "family": "Luo"}],
        authors_source="crossref",
    )
    assert store.get_paper_authors(luo.id)[0]["middle"] == "X."
    assert store.find_papers_by_author(kind="paper", q="Ronggang X. Luo") == [luo.id]


def test_find_papers_by_author_exact_surname_ranks_first(store: Store) -> None:
    exact = store.insert_ref(
        kind="paper",
        slug="exact-luo",
        title="Exact surname match",
        authors=[{"given": "Ronggang", "family": "Luo"}],
    )
    fuzzy = store.insert_ref(
        kind="paper",
        slug="fuzzy-luo",
        title="Fuzzy near-name match",
        authors=[{"name": "Luonan Chen"}],
    )
    hits = store.find_papers_by_author(kind="paper", q="Luo")
    assert hits[0] == exact.id
    assert fuzzy.id in hits


# ── drift health check ──────────────────────────────────────────────


def test_paper_authors_drift_check(store: Store) -> None:
    ref = store.insert_ref(
        kind="paper", slug="drift-ok", title="T", authors=[{"name": "Solo Author"}]
    )
    with store.pool.connection() as conn:
        assert paper_authors_drift(conn) == {"count": 0, "examples": []}
        conn.execute(
            "UPDATE refs SET authors = %s::jsonb WHERE ref_id = %s",
            ('[{"name": "Solo Author"}, {"name": "Ghost Author"}]', ref.id),
        )

    with store.pool.connection() as conn:
        result = paper_authors_drift(conn)
    assert result["count"] == 1
    assert result["examples"] == [ref.id]
