"""Perplexity Sonar handlers — websearch / think / research (Phase 3).

Three distinct kinds sharing a common base class but mapped to different
Perplexity Sonar models.  All three require ``PERPLEXITY_API_KEY`` and
are ImportError-gated on ``httpx`` (part of the ``[external]`` extra).

Ported from ``perplexity-sonar-mcp/src/perplexity_sonar_mcp/server.py``
(the standalone MCP stays installable; this consolidates the same
capability into precis so agents that use the unified precis bundle
don't need a second MCP — §13 Phase 3).

**Naming note (v5.0).** What used to be ``web:`` here is now ``websearch:``.
The scheme ``web:`` was freed up for a stored-bookmark kind (see
``docs/websites-plan.md``).  Live Perplexity search moved under the
literal name ``websearch:``; no alias is retained because ``web:`` is
now a different kind entirely.

Kind map:

    kind        model                      endpoint   typical latency  cost_hint
    websearch   sonar                      /chat      2–5s             ~$0.001/call
    think       sonar-reasoning-pro        /chat      5–30s            ~$0.005/call
    research    sonar-deep-research        /chat      2–10 MIN         ~$0.50/call

All three kinds emit an attribution footer on every return path (§Phase 4
attribution policy, see handler memory).  Perplexity's Terms of Service
prohibit silent embedding of their outputs and require disclosure that
AI generated the content — see
https://www.perplexity.ai/hub/legal/terms-of-service.  The footer also
warns the user that Perplexity is not a primary source: the inline
``[N]`` citations surfaced in the response body are the real sources to
cite, verified independently.
"""

from __future__ import annotations

import logging
import os
from typing import Any, ClassVar

from precis.protocol import CallContext, ErrorCode, Handler, PrecisError

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Endpoint + attribution constants
# ---------------------------------------------------------------------------

_SONAR_URL = "https://api.perplexity.ai/chat/completions"

#: Attribution footer template.  Per
#: https://www.perplexity.ai/hub/legal/terms-of-service, every public /
#: shared output from Perplexity must disclose AI generation; Standard
#: and Pro tiers are restricted to personal/non-commercial use.  The
#: footer also tells the reader to verify the cited sources — inline
#: ``[N]`` citations in the body are preserved verbatim so they can.
_PERPLEXITY_ATTRIBUTION = (
    "---\n"
    "_Answer generated by [Perplexity AI](https://perplexity.ai/) using the "
    "`{model}` model.  Perplexity is not a primary source; the numbered "
    "citations above link to the original sources — verify them before "
    "citing in any publication.  Per Perplexity's [Terms of Service]"
    "(https://www.perplexity.ai/hub/legal/terms-of-service): disclose AI "
    "use in public output; Standard/Pro tiers are for personal / "
    "non-commercial use only (enterprise terms required for commercial use)._"
)


def _attribution(model: str) -> str:
    """Build the Perplexity attribution footer, naming the model used."""
    return _PERPLEXITY_ATTRIBUTION.format(model=model)


# ---------------------------------------------------------------------------
# Shared base
# ---------------------------------------------------------------------------


class _PerplexityBase(Handler):
    """Base for all three Perplexity-backed kinds.

    Subclasses must set the ``scheme``, ``_MODEL`` and ``_TIMEOUT``
    class attributes.  All other behaviour (auth, HTTP call, response
    formatting, attribution) is shared.
    """

    #: Perplexity model identifier (``sonar`` / ``sonar-reasoning-pro`` /
    #: ``sonar-deep-research``).  Subclasses override.
    _MODEL: ClassVar[str] = ""

    #: HTTP timeout in seconds.  Subclasses override per SLA.
    _TIMEOUT: ClassVar[int] = 60

    #: One-line human-readable tagline for the landing view.  Subclasses
    #: override to describe their Sonar mode.
    _TAGLINE: ClassVar[str] = "Perplexity-backed query."

    #: Emoji prefix for the landing header.  Subclasses override.
    _EMOJI: ClassVar[str] = "🌐"

    #: Example invocations listed in the landing view.  Subclasses override.
    _EXAMPLES: ClassVar[tuple[str, ...]] = ()

    writable = False
    views = set()

    # ---- Auth / transport -------------------------------------------

    @staticmethod
    def _get_api_key() -> str:
        """Return the API key, raising KIND_UNAVAILABLE when absent."""
        key = os.environ.get("PERPLEXITY_API_KEY", "").strip()
        if not key:
            raise PrecisError(
                ErrorCode.KIND_UNAVAILABLE,
                "PERPLEXITY_API_KEY environment variable is not set. "
                "Get a key from https://www.perplexity.ai/settings/api.",
            )
        return key

    def _call_sonar(self, query: str) -> dict[str, Any]:
        """POST the query to Perplexity's chat-completions endpoint.

        Separated from :meth:`read` so tests can patch ``_call_sonar``
        without mocking the full ``httpx`` stack when they'd rather
        stub at a higher level.
        """
        try:
            import httpx
        except ImportError as exc:
            raise PrecisError(
                ErrorCode.KIND_UNAVAILABLE,
                "httpx package not installed. "
                "Install with: pip install precis-mcp[external]",
            ) from exc

        api_key = self._get_api_key()
        payload = {
            "model": self._MODEL,
            "messages": [{"role": "user", "content": query}],
            "return_citations": True,
            "web_search_options": {"search_context_size": "high"},
        }
        try:
            resp = httpx.post(
                _SONAR_URL,
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                },
                json=payload,
                timeout=self._TIMEOUT,
            )
            resp.raise_for_status()
            return resp.json()
        except httpx.HTTPStatusError as exc:
            # Shape-specific error so the agent can react (e.g. rate
            # limit → back off; 401 → surface the missing/invalid key).
            status = exc.response.status_code
            if status == 401:
                raise PrecisError(
                    ErrorCode.DENIED,
                    f"Perplexity rejected the API key (HTTP 401). "
                    f"Check PERPLEXITY_API_KEY. Response: {exc.response.text[:200]}",
                ) from exc
            if status == 429:
                raise PrecisError(
                    ErrorCode.RATE_LIMITED,
                    "Perplexity rate limit hit (HTTP 429). "
                    "Retry after a short back-off.",
                ) from exc
            raise PrecisError(
                ErrorCode.UPSTREAM_ERROR,
                f"Perplexity API error (HTTP {status}): {exc.response.text[:200]}",
            ) from exc
        except httpx.TimeoutException as exc:
            raise PrecisError(
                ErrorCode.TIMEOUT,
                f"Perplexity request timed out after {self._TIMEOUT}s "
                f"(model: {self._MODEL}). Try a smaller query or the "
                f"`research` kind for slow-paced multi-step work.",
            ) from exc
        except httpx.HTTPError as exc:
            raise PrecisError(
                ErrorCode.UPSTREAM_ERROR,
                f"Perplexity transport error: {exc}",
            ) from exc

    # ---- Core read --------------------------------------------------

    def read(
        self,
        path: str,
        selector: str | None,
        view: str | None,
        subview: str | None,
        query: str,
        summarize: bool,
        depth: int,
        page: int,
        **_ignore,
    ) -> str:
        """Query Perplexity and return the answer + citations + attribution.

        The URI ``<kind>:<question>`` is parsed so that ``path`` is the
        question.  ``query`` (the ``search``-style filter parameter) is
        accepted as a fallback when the caller used the search tool
        with an empty id.  Other handler params are ignored — a Sonar
        answer is atomic, so ``top_k`` and similar kwargs forwarded by
        the ``search()`` dispatcher are absorbed by ``**_ignore`` rather
        than raising ``TypeError``.  This matters for ``search(type=
        '<web|research|think>', query=…)`` which routes through
        ``tools.read`` and always carries ``top_k``.

        A bare call (``get(id='<scheme>:')`` with no query) returns a
        landing view describing the kind — no API call is made and the
        response is free (see :meth:`cost_of`).
        """
        question = (path or query or "").strip()
        if not question:
            return self._landing()
        data = self._call_sonar(question)
        return _format_response(data, self._MODEL)

    # ---- Landing / cost hooks --------------------------------------

    def _landing(self) -> str:
        """Render the help/landing view shown on a bare call.

        Purely informational — no Perplexity API call, no key required.
        Pairs with :meth:`cost_of` to report ``free`` for this path so
        agents aren't misled by the kind-level ``cost_hint``.
        """
        lines = [
            f"{self._EMOJI} {self.scheme}: — {self._TAGLINE}",
            "",
            (
                f"Model: `{self._MODEL}` · timeout: {self._TIMEOUT}s · "
                f"requires `PERPLEXITY_API_KEY`"
            ),
            "",
            "Usage:",
            f"  get(type='{self.scheme}', id='<question>')",
            f"  search(type='{self.scheme}', query='<question>')",
        ]
        if self._EXAMPLES:
            lines.append("")
            lines.append("Examples:")
            for ex in self._EXAMPLES:
                lines.append(f"  {ex}")
        lines.append("")
        lines.append(
            "Answers include numbered source citations; verify sources "
            "before citing in publications — Perplexity is not a primary "
            "source."
        )
        return "\n".join(lines)

    def cost_of(self, ctx: CallContext) -> str | None:
        """Report ``free`` for bare-landing calls, else fall back to spec.

        A bare call never hits the Perplexity API; the kind-level
        ``cost_hint`` (``~$0.001/call`` etc.) would be misleading on
        the landing response.  Returning ``None`` for non-landing calls
        lets the registry's three-level fallback emit the per-kind hint.
        """
        raw_id = str(ctx.args.get("id", "")).strip()
        grep = str(ctx.args.get("grep", "")).strip()
        query = str(ctx.args.get("query", "")).strip()
        # Strip the scheme prefix if present so "web:" and "web" both count.
        prefix = f"{self.scheme}:"
        if raw_id.startswith(prefix):
            raw_id = raw_id[len(prefix) :].strip()
        if not raw_id and not grep and not query:
            return "free"
        return None


# ---------------------------------------------------------------------------
# Response formatter — shared across modes
# ---------------------------------------------------------------------------


def _format_response(data: dict[str, Any], model: str) -> str:
    """Render the Perplexity response as compact markdown + attribution.

    Preserves inline ``[N]`` markers from Perplexity's content exactly
    as returned, and appends a ``Sources:`` list of the underlying URLs
    so the user can verify each claim against the primary source.
    Attribution footer is appended per the Phase 4 policy.
    """
    choices = data.get("choices") or []
    if not choices:
        return "Perplexity returned no answer (empty `choices`).\n\n" + _attribution(
            model
        )

    message = choices[0].get("message") or {}
    content = str(message.get("content") or "").strip()
    citations = data.get("citations") or []

    parts: list[str] = []
    if content:
        parts.append(content)
    else:
        parts.append("_(Perplexity returned an empty answer.)_")

    if citations:
        parts.append("")
        parts.append("Sources:")
        for i, url in enumerate(citations, 1):
            parts.append(f"[{i}] {url}")

    parts.append("")
    parts.append(_attribution(model))
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Mode subclasses — one per registered kind
# ---------------------------------------------------------------------------


class WebsearchHandler(_PerplexityBase):
    """``websearch:`` — Sonar (fast factual search).

    Agent usage::

        get(type='websearch', id='current CEO of Anthropic')
        search(query='Perseverance rover findings 2025', type='websearch')
    """

    scheme = "websearch"
    _MODEL: ClassVar[str] = "sonar"
    _TIMEOUT: ClassVar[int] = 30
    _TAGLINE: ClassVar[str] = "Perplexity Sonar — fast factual web search"
    _EMOJI: ClassVar[str] = "🌐"
    _EXAMPLES: ClassVar[tuple[str, ...]] = (
        "get(type='websearch', id='current CEO of Anthropic')",
        "search(type='websearch', query='Perseverance rover findings 2025')",
    )


class ThinkHandler(_PerplexityBase):
    """``think:`` — Sonar Reasoning Pro (detailed analysis + reasoning).

    Agent usage::

        get(type='think', id='compare GPT-4o and Claude 4 on code review')
    """

    scheme = "think"
    _MODEL: ClassVar[str] = "sonar-reasoning-pro"
    _TIMEOUT: ClassVar[int] = 120
    _TAGLINE: ClassVar[str] = (
        "Perplexity Sonar Reasoning Pro — detailed analysis with reasoning traces"
    )
    _EMOJI: ClassVar[str] = "🧠"
    _EXAMPLES: ClassVar[tuple[str, ...]] = (
        "get(type='think', id='compare GPT-4o and Claude 4 on code review')",
        "get(type='think', id='why does Postgres SKIP LOCKED help here?')",
    )


class ResearchHandler(_PerplexityBase):
    """``research:`` — Sonar Deep Research (multi-step, minutes-long).

    Agent usage::

        get(type='research', id='landscape of post-quantum signature schemes')

    Warning: calls can take 2–10 minutes and cost ~$0.50 each.  Use
    only for research questions that justify the wait and expense.
    """

    scheme = "research"
    _MODEL: ClassVar[str] = "sonar-deep-research"
    _TIMEOUT: ClassVar[int] = 600
    _TAGLINE: ClassVar[str] = (
        "Perplexity Sonar Deep Research — multi-step research (minutes, ~$0.50/call)"
    )
    _EMOJI: ClassVar[str] = "🔬"
    _EXAMPLES: ClassVar[tuple[str, ...]] = (
        "get(type='research', id='landscape of post-quantum signature schemes')",
        "get(type='research', id='compare AEM vs PEM for CO2 reduction')",
    )
