-- 0001_initial.sql — second greenfield (2026-06-05)
--
-- Snapshot of the precis-mcp schema from the cluster master after
-- migrations 0001 through 0017 had landed. See ADR 0019 for the
-- rationale (sustained bug-fix run during which sealed migrations
-- 0001 / 0002 / 0009 / 0010 were edited post-seal, accumulating
-- checksum drift the runner now refuses to verify).
--
-- Replaces the original `0001_initial.sql` plus migrations 0002–0017.
-- Those files are preserved under `migrations/archive/` for history
-- and have been removed from the runner's discovery path.
--
-- Forward-only discipline still applies: do not edit this file
-- once sealed. Any change ships as a new forward migration.
--
-- Generated by `pg_dump --schema=public --schema-only` against the
-- cluster master (PostgreSQL 17.10), followed by selective
-- `--data-only` for the seed vocabulary tables (actors, kinds,
-- relations, providers, chunk_kinds, embedders, summarizers,
-- artifact_kinds).

-- ===========================================================================
-- Extensions (pgvector / trigram / btree_gist)
-- ===========================================================================

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ===========================================================================
-- Schema (tables, indexes, constraints, types)
-- ===========================================================================
--
--

\restrict bOkWOHHSbFvrOMSBMgBVS0iSC6pczc2EiRpJKCoeDiXur7b4Pgg6YuLxB6WQAy3


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS public;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: _migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public._migrations (
    version text NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL,
    checksum text NOT NULL
);


--
-- Name: actors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.actors (
    slug text NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: app_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_state (
    key text NOT NULL,
    value text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: artifact_kinds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.artifact_kinds (
    slug text NOT NULL,
    target text NOT NULL,
    storage text NOT NULL,
    output_table text NOT NULL,
    description text,
    deprecated_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT artifact_kinds_storage_check CHECK ((storage = ANY (ARRAY['typed'::text, 'untyped'::text]))),
    CONSTRAINT artifact_kinds_target_check CHECK ((target = ANY (ARRAY['chunk'::text, 'ref'::text, 'link'::text, 'pdf'::text, 'tag'::text])))
);


--
-- Name: cache_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cache_state (
    ref_id bigint NOT NULL,
    provider text NOT NULL,
    request_hash text NOT NULL,
    model text,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    fresh_until timestamp with time zone,
    cost_usd numeric,
    meta jsonb DEFAULT '{}'::jsonb NOT NULL
);


--
-- Name: chunk_embeddings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chunk_embeddings (
    chunk_id bigint NOT NULL,
    embedder text NOT NULL,
    vector public.vector(1024),
    status text DEFAULT 'ok'::text NOT NULL,
    attempts integer DEFAULT 1 NOT NULL,
    last_error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chunk_embeddings_status_check CHECK ((status = ANY (ARRAY['ok'::text, 'failed'::text])))
);


--
-- Name: chunk_kinds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chunk_kinds (
    slug text NOT NULL,
    is_card boolean DEFAULT false NOT NULL,
    description text,
    deprecated_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: chunk_summaries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chunk_summaries (
    chunk_id bigint NOT NULL,
    summarizer text NOT NULL,
    text text,
    prompt_hash character(64),
    token_count integer,
    status text DEFAULT 'ok'::text NOT NULL,
    attempts integer DEFAULT 1 NOT NULL,
    last_error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chunk_summaries_status_check CHECK ((status = ANY (ARRAY['ok'::text, 'failed'::text])))
);


--
-- Name: chunk_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chunk_tags (
    chunk_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    set_by text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: chunks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chunks (
    chunk_id bigint NOT NULL,
    ref_id bigint NOT NULL,
    set_by text,
    ord integer NOT NULL,
    chunk_kind text NOT NULL,
    text text NOT NULL,
    block_ids bigint[] DEFAULT '{}'::bigint[] NOT NULL,
    token_count integer,
    section_path text[] DEFAULT '{}'::text[] NOT NULL,
    page_first integer,
    page_last integer,
    meta jsonb DEFAULT '{}'::jsonb NOT NULL,
    tsv tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, text)) STORED,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    numerics text[] DEFAULT '{}'::text[] NOT NULL,
    keywords text[],
    keywords_meta jsonb,
    CONSTRAINT chunks_check CHECK ((((ord < 0) AND (chunk_kind ~~ 'card_%'::text)) OR ((ord >= 0) AND (chunk_kind !~~ 'card_%'::text)))),
    CONSTRAINT chunks_check1 CHECK (((page_first IS NULL) OR (page_last IS NULL) OR (page_first <= page_last)))
);


--
-- Name: chunks_chunk_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.chunks_chunk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: chunks_chunk_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.chunks_chunk_id_seq OWNED BY public.chunks.chunk_id;


--
-- Name: embedders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.embedders (
    name text NOT NULL,
    dim integer NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    description text,
    deprecated_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: kinds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kinds (
    slug text NOT NULL,
    is_numeric boolean DEFAULT false NOT NULL,
    title text NOT NULL,
    description text,
    deprecated_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.links (
    link_id bigint NOT NULL,
    src_ref_id bigint NOT NULL,
    src_chunk_id bigint,
    dst_ref_id bigint NOT NULL,
    dst_chunk_id bigint,
    relation text NOT NULL,
    set_by text NOT NULL,
    meta jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT links_check CHECK ((NOT ((src_ref_id = dst_ref_id) AND (NOT (src_chunk_id IS DISTINCT FROM dst_chunk_id)))))
);


--
-- Name: links_link_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.links_link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: links_link_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.links_link_id_seq OWNED BY public.links.link_id;


--
-- Name: patent_watches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patent_watches (
    id bigint NOT NULL,
    name text NOT NULL,
    cql text NOT NULL,
    interval_s integer NOT NULL,
    auto_get boolean DEFAULT false NOT NULL,
    max_per_pass integer,
    last_run_at timestamp with time zone,
    last_seen_pn text[],
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by text NOT NULL,
    CONSTRAINT patent_watches_interval_s_check CHECK ((interval_s > 0)),
    CONSTRAINT patent_watches_max_per_pass_check CHECK (((max_per_pass IS NULL) OR (max_per_pass > 0)))
);


--
-- Name: patent_watches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.patent_watches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: patent_watches_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.patent_watches_id_seq OWNED BY public.patent_watches.id;


--
-- Name: pdfs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pdfs (
    pdf_sha256 character(64) NOT NULL,
    content_hash character(64) NOT NULL,
    page_count integer NOT NULL,
    size_bytes bigint NOT NULL,
    storage_path text NOT NULL,
    ingested_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: provenance_rw_cache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provenance_rw_cache (
    record_id bigint NOT NULL,
    paper_doi text NOT NULL,
    notice_doi text,
    notice_nature text NOT NULL,
    reasons text[] DEFAULT '{}'::text[] NOT NULL,
    retraction_date date,
    paper_title text,
    journal text,
    raw jsonb DEFAULT '{}'::jsonb NOT NULL,
    synced_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: provenance_rw_sync; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provenance_rw_sync (
    source_url text NOT NULL,
    last_full_sync_at timestamp with time zone,
    last_row_count integer,
    last_status text,
    last_error text
);


--
-- Name: providers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.providers (
    slug text NOT NULL,
    description text,
    deprecated_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: ref_artifacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ref_artifacts (
    ref_id bigint NOT NULL,
    artifact text NOT NULL,
    payload jsonb,
    status text DEFAULT 'ok'::text NOT NULL,
    attempts integer DEFAULT 1 NOT NULL,
    last_error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ref_artifacts_status_check CHECK ((status = ANY (ARRAY['ok'::text, 'failed'::text])))
);


--
-- Name: ref_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ref_events (
    event_id bigint NOT NULL,
    ref_id bigint NOT NULL,
    ts timestamp with time zone DEFAULT now() NOT NULL,
    source text NOT NULL,
    event text NOT NULL,
    payload jsonb,
    duration_ms integer,
    cost_usd numeric
);


--
-- Name: ref_events_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.ref_events_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ref_events_event_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.ref_events_event_id_seq OWNED BY public.ref_events.event_id;


--
-- Name: ref_identifiers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ref_identifiers (
    id_kind text NOT NULL,
    id_value text NOT NULL,
    ref_id bigint NOT NULL,
    source text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: ref_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ref_tags (
    ref_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    set_by text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: refs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refs (
    ref_id bigint NOT NULL,
    kind text NOT NULL,
    set_by text,
    title text NOT NULL,
    authors jsonb,
    year integer,
    provider text,
    human_verified_at timestamp with time zone,
    human_verified_by text,
    human_verified_note text,
    retraction_status text,
    retracted_at timestamp with time zone,
    retraction_reason text,
    retraction_url text,
    retraction_checked_at timestamp with time zone,
    pdf_sha256 character(64),
    pdf_pages int4range,
    pdf_role text,
    meta jsonb DEFAULT '{}'::jsonb NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT refs_pdf_role_check CHECK (((pdf_role IS NULL) OR (pdf_role = ANY (ARRAY['main'::text, 'supplement'::text, 'appendix'::text, 'front_matter'::text, 'back_matter'::text])))),
    CONSTRAINT refs_retraction_status_check CHECK (((retraction_status IS NULL) OR (retraction_status = ANY (ARRAY['retracted'::text, 'corrected'::text, 'expression_of_concern'::text]))))
);


--
-- Name: refs_ref_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.refs_ref_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: refs_ref_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.refs_ref_id_seq OWNED BY public.refs.ref_id;


--
-- Name: relations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relations (
    slug text NOT NULL,
    is_symmetric boolean DEFAULT false NOT NULL,
    inverse_slug text,
    description text,
    deprecated_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: summarizers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.summarizers (
    name text NOT NULL,
    prompt_template text,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    description text,
    deprecated_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: tag_embeddings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tag_embeddings (
    namespace text NOT NULL,
    value text NOT NULL,
    vector public.vector(1024),
    version integer DEFAULT 1 NOT NULL,
    embedder text NOT NULL,
    embedded_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tags (
    tag_id bigint NOT NULL,
    namespace text NOT NULL,
    value text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT tags_namespace_check CHECK (((namespace = upper(namespace)) AND (namespace <> ''::text))),
    CONSTRAINT tags_value_check CHECK ((value <> ''::text))
);


--
-- Name: tags_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tags_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tags_tag_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tags_tag_id_seq OWNED BY public.tags.tag_id;


--
-- Name: v_chunk_tags_all; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_chunk_tags_all AS
 SELECT ct.chunk_id,
    t.tag_id,
    t.namespace,
    t.value,
    'direct'::text AS via,
    ct.set_by,
    ct.created_at
   FROM (public.chunk_tags ct
     JOIN public.tags t USING (tag_id))
UNION ALL
 SELECT c.chunk_id,
    t.tag_id,
    t.namespace,
    t.value,
    'ref'::text AS via,
    rt.set_by,
    rt.created_at
   FROM ((public.ref_tags rt
     JOIN public.tags t USING (tag_id))
     JOIN public.chunks c USING (ref_id));


--
-- Name: v_ref_tags_all; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_ref_tags_all AS
 SELECT rt.ref_id,
    t.tag_id,
    t.namespace,
    t.value,
    'direct'::text AS via,
    NULL::bigint AS chunk_id,
    rt.set_by,
    rt.created_at
   FROM (public.ref_tags rt
     JOIN public.tags t USING (tag_id))
UNION ALL
 SELECT c.ref_id,
    t.tag_id,
    t.namespace,
    t.value,
    'chunk'::text AS via,
    c.chunk_id,
    ct.set_by,
    ct.created_at
   FROM ((public.chunk_tags ct
     JOIN public.chunks c USING (chunk_id))
     JOIN public.tags t USING (tag_id));


--
-- Name: v_refs; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_refs AS
 SELECT ref_id,
    kind,
    set_by,
    title,
    authors,
    year,
    provider,
    human_verified_at,
    human_verified_by,
    human_verified_note,
    retraction_status,
    retracted_at,
    retraction_reason,
    retraction_url,
    retraction_checked_at,
    pdf_sha256,
    pdf_pages,
    pdf_role,
    meta,
    deleted_at,
    created_at,
    updated_at,
    ( SELECT ref_identifiers.id_value
           FROM public.ref_identifiers
          WHERE ((ref_identifiers.ref_id = r.ref_id) AND (ref_identifiers.id_kind = 'pub_id'::text))) AS pub_id,
    ( SELECT ref_identifiers.id_value
           FROM public.ref_identifiers
          WHERE ((ref_identifiers.ref_id = r.ref_id) AND (ref_identifiers.id_kind = 'cite_key'::text))) AS cite_key,
    ( SELECT ref_identifiers.id_value
           FROM public.ref_identifiers
          WHERE ((ref_identifiers.ref_id = r.ref_id) AND (ref_identifiers.id_kind = 'paper_id'::text))) AS paper_id
   FROM public.refs r;


--
-- Name: chunks chunk_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunks ALTER COLUMN chunk_id SET DEFAULT nextval('public.chunks_chunk_id_seq'::regclass);


--
-- Name: links link_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.links ALTER COLUMN link_id SET DEFAULT nextval('public.links_link_id_seq'::regclass);


--
-- Name: patent_watches id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patent_watches ALTER COLUMN id SET DEFAULT nextval('public.patent_watches_id_seq'::regclass);


--
-- Name: ref_events event_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_events ALTER COLUMN event_id SET DEFAULT nextval('public.ref_events_event_id_seq'::regclass);


--
-- Name: refs ref_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refs ALTER COLUMN ref_id SET DEFAULT nextval('public.refs_ref_id_seq'::regclass);


--
-- Name: tags tag_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags ALTER COLUMN tag_id SET DEFAULT nextval('public.tags_tag_id_seq'::regclass);


--
-- Name: _migrations _migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public._migrations
    ADD CONSTRAINT _migrations_pkey PRIMARY KEY (version);


--
-- Name: actors actors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actors
    ADD CONSTRAINT actors_pkey PRIMARY KEY (slug);


--
-- Name: app_state app_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_state
    ADD CONSTRAINT app_state_pkey PRIMARY KEY (key);


--
-- Name: artifact_kinds artifact_kinds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artifact_kinds
    ADD CONSTRAINT artifact_kinds_pkey PRIMARY KEY (slug);


--
-- Name: cache_state cache_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cache_state
    ADD CONSTRAINT cache_state_pkey PRIMARY KEY (ref_id);


--
-- Name: cache_state cache_state_provider_request_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cache_state
    ADD CONSTRAINT cache_state_provider_request_hash_key UNIQUE (provider, request_hash);


--
-- Name: chunk_embeddings chunk_embeddings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunk_embeddings
    ADD CONSTRAINT chunk_embeddings_pkey PRIMARY KEY (chunk_id, embedder);


--
-- Name: chunk_kinds chunk_kinds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunk_kinds
    ADD CONSTRAINT chunk_kinds_pkey PRIMARY KEY (slug);


--
-- Name: chunk_summaries chunk_summaries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunk_summaries
    ADD CONSTRAINT chunk_summaries_pkey PRIMARY KEY (chunk_id, summarizer);


--
-- Name: chunk_tags chunk_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunk_tags
    ADD CONSTRAINT chunk_tags_pkey PRIMARY KEY (chunk_id, tag_id);


--
-- Name: chunks chunks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunks
    ADD CONSTRAINT chunks_pkey PRIMARY KEY (chunk_id);


--
-- Name: chunks chunks_ref_id_ord_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunks
    ADD CONSTRAINT chunks_ref_id_ord_key UNIQUE (ref_id, ord);


--
-- Name: embedders embedders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embedders
    ADD CONSTRAINT embedders_pkey PRIMARY KEY (name);


--
-- Name: kinds kinds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kinds
    ADD CONSTRAINT kinds_pkey PRIMARY KEY (slug);


--
-- Name: links links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.links
    ADD CONSTRAINT links_pkey PRIMARY KEY (link_id);


--
-- Name: patent_watches patent_watches_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patent_watches
    ADD CONSTRAINT patent_watches_name_key UNIQUE (name);


--
-- Name: patent_watches patent_watches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patent_watches
    ADD CONSTRAINT patent_watches_pkey PRIMARY KEY (id);


--
-- Name: pdfs pdfs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pdfs
    ADD CONSTRAINT pdfs_pkey PRIMARY KEY (pdf_sha256);


--
-- Name: provenance_rw_cache provenance_rw_cache_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provenance_rw_cache
    ADD CONSTRAINT provenance_rw_cache_pkey PRIMARY KEY (record_id);


--
-- Name: provenance_rw_sync provenance_rw_sync_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provenance_rw_sync
    ADD CONSTRAINT provenance_rw_sync_pkey PRIMARY KEY (source_url);


--
-- Name: providers providers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.providers
    ADD CONSTRAINT providers_pkey PRIMARY KEY (slug);


--
-- Name: ref_artifacts ref_artifacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_artifacts
    ADD CONSTRAINT ref_artifacts_pkey PRIMARY KEY (ref_id, artifact);


--
-- Name: ref_events ref_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_events
    ADD CONSTRAINT ref_events_pkey PRIMARY KEY (event_id);


--
-- Name: ref_identifiers ref_identifiers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_identifiers
    ADD CONSTRAINT ref_identifiers_pkey PRIMARY KEY (id_kind, id_value);


--
-- Name: ref_tags ref_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_tags
    ADD CONSTRAINT ref_tags_pkey PRIMARY KEY (ref_id, tag_id);


--
-- Name: refs refs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refs
    ADD CONSTRAINT refs_pkey PRIMARY KEY (ref_id);


--
-- Name: relations relations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.relations
    ADD CONSTRAINT relations_pkey PRIMARY KEY (slug);


--
-- Name: summarizers summarizers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.summarizers
    ADD CONSTRAINT summarizers_pkey PRIMARY KEY (name);


--
-- Name: tag_embeddings tag_embeddings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tag_embeddings
    ADD CONSTRAINT tag_embeddings_pkey PRIMARY KEY (namespace, value);


--
-- Name: tags tags_namespace_value_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_namespace_value_key UNIQUE (namespace, value);


--
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (tag_id);


--
-- Name: cache_state_fresh_until_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cache_state_fresh_until_idx ON public.cache_state USING btree (fresh_until) WHERE (fresh_until IS NOT NULL);


--
-- Name: cache_state_provider_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cache_state_provider_idx ON public.cache_state USING btree (provider);


--
-- Name: chunk_embeddings_failed_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chunk_embeddings_failed_idx ON public.chunk_embeddings USING btree (chunk_id, embedder) WHERE (status = 'failed'::text);


--
-- Name: chunk_embeddings_vec_hnsw_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chunk_embeddings_vec_hnsw_idx ON public.chunk_embeddings USING hnsw (vector public.vector_cosine_ops) WHERE ((status = 'ok'::text) AND (vector IS NOT NULL));


--
-- Name: chunk_summaries_failed_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chunk_summaries_failed_idx ON public.chunk_summaries USING btree (chunk_id, summarizer) WHERE (status = 'failed'::text);


--
-- Name: chunk_tags_tag_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chunk_tags_tag_id_idx ON public.chunk_tags USING btree (tag_id);


--
-- Name: chunks_cards_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chunks_cards_idx ON public.chunks USING btree (ref_id, ord) WHERE (ord < 0);


--
-- Name: chunks_chunk_kind_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chunks_chunk_kind_idx ON public.chunks USING btree (chunk_kind);


--
-- Name: chunks_keywords_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chunks_keywords_gin ON public.chunks USING gin (keywords);


--
-- Name: chunks_numerics_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chunks_numerics_idx ON public.chunks USING gin (numerics);


--
-- Name: chunks_ref_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chunks_ref_id_idx ON public.chunks USING btree (ref_id);


--
-- Name: chunks_section_path_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chunks_section_path_idx ON public.chunks USING gin (section_path);


--
-- Name: chunks_tsv_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chunks_tsv_idx ON public.chunks USING gin (tsv);


--
-- Name: embedders_one_default_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX embedders_one_default_idx ON public.embedders USING btree (is_default) WHERE (is_default = true);


--
-- Name: links_dst_chunk_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX links_dst_chunk_idx ON public.links USING btree (dst_chunk_id) WHERE (dst_chunk_id IS NOT NULL);


--
-- Name: links_dst_ref_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX links_dst_ref_idx ON public.links USING btree (dst_ref_id);


--
-- Name: links_endpoints_relation_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX links_endpoints_relation_idx ON public.links USING btree (src_ref_id, src_chunk_id, dst_ref_id, dst_chunk_id, relation) NULLS NOT DISTINCT;


--
-- Name: links_relation_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX links_relation_idx ON public.links USING btree (relation);


--
-- Name: links_src_chunk_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX links_src_chunk_idx ON public.links USING btree (src_chunk_id) WHERE (src_chunk_id IS NOT NULL);


--
-- Name: links_src_ref_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX links_src_ref_idx ON public.links USING btree (src_ref_id);


--
-- Name: patent_watches_due_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patent_watches_due_idx ON public.patent_watches USING btree (last_run_at NULLS FIRST);


--
-- Name: pdfs_content_hash_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pdfs_content_hash_idx ON public.pdfs USING btree (content_hash);


--
-- Name: provenance_rw_notice_doi_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX provenance_rw_notice_doi_idx ON public.provenance_rw_cache USING btree (notice_doi) WHERE (notice_doi IS NOT NULL);


--
-- Name: provenance_rw_paper_doi_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX provenance_rw_paper_doi_idx ON public.provenance_rw_cache USING btree (paper_doi);


--
-- Name: ref_artifacts_artifact_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ref_artifacts_artifact_idx ON public.ref_artifacts USING btree (artifact);


--
-- Name: ref_artifacts_failed_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ref_artifacts_failed_idx ON public.ref_artifacts USING btree (ref_id, artifact) WHERE (status = 'failed'::text);


--
-- Name: ref_events_ref_id_ts_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ref_events_ref_id_ts_idx ON public.ref_events USING btree (ref_id, ts DESC);


--
-- Name: ref_events_source_event_ts_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ref_events_source_event_ts_idx ON public.ref_events USING btree (source, event, ts DESC);


--
-- Name: ref_identifiers_cite_key_trgm_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ref_identifiers_cite_key_trgm_idx ON public.ref_identifiers USING gin (id_value public.gin_trgm_ops) WHERE (id_kind = 'cite_key'::text);


--
-- Name: ref_identifiers_ref_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ref_identifiers_ref_id_idx ON public.ref_identifiers USING btree (ref_id);


--
-- Name: ref_tags_tag_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ref_tags_tag_id_idx ON public.ref_tags USING btree (tag_id);


--
-- Name: refs_alive_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX refs_alive_idx ON public.refs USING btree (kind, year) WHERE (deleted_at IS NULL);


--
-- Name: refs_human_verified_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX refs_human_verified_idx ON public.refs USING btree (human_verified_at) WHERE (human_verified_at IS NOT NULL);


--
-- Name: refs_kind_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX refs_kind_idx ON public.refs USING btree (kind);


--
-- Name: refs_pdf_sha256_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX refs_pdf_sha256_idx ON public.refs USING btree (pdf_sha256) WHERE (pdf_sha256 IS NOT NULL);


--
-- Name: refs_provider_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX refs_provider_idx ON public.refs USING btree (provider) WHERE (provider IS NOT NULL);


--
-- Name: refs_retraction_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX refs_retraction_idx ON public.refs USING btree (retraction_status) WHERE (retraction_status IS NOT NULL);


--
-- Name: refs_year_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX refs_year_idx ON public.refs USING btree (year) WHERE (year IS NOT NULL);


--
-- Name: summarizers_one_default_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX summarizers_one_default_idx ON public.summarizers USING btree (is_default) WHERE (is_default = true);


--
-- Name: tag_embeddings_vector_hnsw; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tag_embeddings_vector_hnsw ON public.tag_embeddings USING hnsw (vector public.vector_cosine_ops);


--
-- Name: tags_namespace_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tags_namespace_idx ON public.tags USING btree (namespace);


--
-- Name: cache_state cache_state_provider_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cache_state
    ADD CONSTRAINT cache_state_provider_fkey FOREIGN KEY (provider) REFERENCES public.providers(slug) ON UPDATE CASCADE;


--
-- Name: cache_state cache_state_ref_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cache_state
    ADD CONSTRAINT cache_state_ref_id_fkey FOREIGN KEY (ref_id) REFERENCES public.refs(ref_id) ON DELETE CASCADE;


--
-- Name: chunk_embeddings chunk_embeddings_chunk_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunk_embeddings
    ADD CONSTRAINT chunk_embeddings_chunk_id_fkey FOREIGN KEY (chunk_id) REFERENCES public.chunks(chunk_id) ON DELETE CASCADE;


--
-- Name: chunk_embeddings chunk_embeddings_embedder_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunk_embeddings
    ADD CONSTRAINT chunk_embeddings_embedder_fkey FOREIGN KEY (embedder) REFERENCES public.embedders(name) ON UPDATE CASCADE;


--
-- Name: chunk_summaries chunk_summaries_chunk_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunk_summaries
    ADD CONSTRAINT chunk_summaries_chunk_id_fkey FOREIGN KEY (chunk_id) REFERENCES public.chunks(chunk_id) ON DELETE CASCADE;


--
-- Name: chunk_summaries chunk_summaries_summarizer_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunk_summaries
    ADD CONSTRAINT chunk_summaries_summarizer_fkey FOREIGN KEY (summarizer) REFERENCES public.summarizers(name) ON UPDATE CASCADE;


--
-- Name: chunk_tags chunk_tags_chunk_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunk_tags
    ADD CONSTRAINT chunk_tags_chunk_id_fkey FOREIGN KEY (chunk_id) REFERENCES public.chunks(chunk_id) ON DELETE CASCADE;


--
-- Name: chunk_tags chunk_tags_set_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunk_tags
    ADD CONSTRAINT chunk_tags_set_by_fkey FOREIGN KEY (set_by) REFERENCES public.actors(slug) ON UPDATE CASCADE;


--
-- Name: chunk_tags chunk_tags_tag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunk_tags
    ADD CONSTRAINT chunk_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(tag_id) ON DELETE CASCADE;


--
-- Name: chunks chunks_chunk_kind_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunks
    ADD CONSTRAINT chunks_chunk_kind_fkey FOREIGN KEY (chunk_kind) REFERENCES public.chunk_kinds(slug) ON UPDATE CASCADE;


--
-- Name: chunks chunks_ref_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunks
    ADD CONSTRAINT chunks_ref_id_fkey FOREIGN KEY (ref_id) REFERENCES public.refs(ref_id) ON DELETE CASCADE;


--
-- Name: chunks chunks_set_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunks
    ADD CONSTRAINT chunks_set_by_fkey FOREIGN KEY (set_by) REFERENCES public.actors(slug) ON UPDATE CASCADE;


--
-- Name: links links_dst_chunk_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.links
    ADD CONSTRAINT links_dst_chunk_id_fkey FOREIGN KEY (dst_chunk_id) REFERENCES public.chunks(chunk_id) ON DELETE CASCADE;


--
-- Name: links links_dst_ref_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.links
    ADD CONSTRAINT links_dst_ref_id_fkey FOREIGN KEY (dst_ref_id) REFERENCES public.refs(ref_id) ON DELETE CASCADE;


--
-- Name: links links_relation_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.links
    ADD CONSTRAINT links_relation_fkey FOREIGN KEY (relation) REFERENCES public.relations(slug) ON UPDATE CASCADE;


--
-- Name: links links_set_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.links
    ADD CONSTRAINT links_set_by_fkey FOREIGN KEY (set_by) REFERENCES public.actors(slug) ON UPDATE CASCADE;


--
-- Name: links links_src_chunk_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.links
    ADD CONSTRAINT links_src_chunk_id_fkey FOREIGN KEY (src_chunk_id) REFERENCES public.chunks(chunk_id) ON DELETE CASCADE;


--
-- Name: links links_src_ref_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.links
    ADD CONSTRAINT links_src_ref_id_fkey FOREIGN KEY (src_ref_id) REFERENCES public.refs(ref_id) ON DELETE CASCADE;


--
-- Name: ref_artifacts ref_artifacts_artifact_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_artifacts
    ADD CONSTRAINT ref_artifacts_artifact_fkey FOREIGN KEY (artifact) REFERENCES public.artifact_kinds(slug) ON UPDATE CASCADE;


--
-- Name: ref_artifacts ref_artifacts_ref_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_artifacts
    ADD CONSTRAINT ref_artifacts_ref_id_fkey FOREIGN KEY (ref_id) REFERENCES public.refs(ref_id) ON DELETE CASCADE;


--
-- Name: ref_events ref_events_ref_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_events
    ADD CONSTRAINT ref_events_ref_id_fkey FOREIGN KEY (ref_id) REFERENCES public.refs(ref_id) ON DELETE CASCADE;


--
-- Name: ref_identifiers ref_identifiers_ref_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_identifiers
    ADD CONSTRAINT ref_identifiers_ref_id_fkey FOREIGN KEY (ref_id) REFERENCES public.refs(ref_id) ON DELETE CASCADE;


--
-- Name: ref_tags ref_tags_ref_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_tags
    ADD CONSTRAINT ref_tags_ref_id_fkey FOREIGN KEY (ref_id) REFERENCES public.refs(ref_id) ON DELETE CASCADE;


--
-- Name: ref_tags ref_tags_set_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_tags
    ADD CONSTRAINT ref_tags_set_by_fkey FOREIGN KEY (set_by) REFERENCES public.actors(slug) ON UPDATE CASCADE;


--
-- Name: ref_tags ref_tags_tag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_tags
    ADD CONSTRAINT ref_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(tag_id) ON DELETE CASCADE;


--
-- Name: refs refs_kind_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refs
    ADD CONSTRAINT refs_kind_fkey FOREIGN KEY (kind) REFERENCES public.kinds(slug) ON UPDATE CASCADE;


--
-- Name: refs refs_pdf_sha256_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refs
    ADD CONSTRAINT refs_pdf_sha256_fkey FOREIGN KEY (pdf_sha256) REFERENCES public.pdfs(pdf_sha256) ON DELETE SET NULL;


--
-- Name: refs refs_provider_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refs
    ADD CONSTRAINT refs_provider_fkey FOREIGN KEY (provider) REFERENCES public.providers(slug) ON UPDATE CASCADE;


--
-- Name: refs refs_set_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refs
    ADD CONSTRAINT refs_set_by_fkey FOREIGN KEY (set_by) REFERENCES public.actors(slug) ON UPDATE CASCADE;


--
--

\unrestrict bOkWOHHSbFvrOMSBMgBVS0iSC6pczc2EiRpJKCoeDiXur7b4Pgg6YuLxB6WQAy3


-- ===========================================================================
-- Seed data (closed vocabulary tables)
-- ===========================================================================
--
--

\restrict ydN3OtexeAo5wgMMm4wlYYswxG1X3mJPqoFdhMRle7WFa87pq9skqXcqrIauHFu


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: actors; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.actors (slug, description, created_at) FROM stdin;
agent	LLM-mediated tool call	2026-05-21 20:06:05.179981+00
user	Direct human invocation (CLI, ops)	2026-05-21 20:06:05.179981+00
system	Server-side automation: sweeps, derived state, defaults	2026-05-21 20:06:05.179981+00
chase	Citation-chase worker — automated agent that traces findings to their primary sources and flags misattributions along the chain. See docs/design/finding-chase.md.	2026-05-30 21:33:14.261241+00
\.


--
-- Data for Name: artifact_kinds; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.artifact_kinds (slug, target, storage, output_table, description, deprecated_at, created_at) FROM stdin;
embed:bge-m3	chunk	typed	chunk_embeddings	BGE-M3 1024-dim dense vector	\N	2026-05-30 21:33:14.261241+00
summarize:rake-lemma	chunk	typed	chunk_summaries	RAKE keyword summary (scispacy-lemmatised)	\N	2026-05-30 21:33:14.261241+00
chase_citation	ref	untyped	ref_artifacts	Citation-chase pass result (one hop or terminal)	\N	2026-05-30 21:33:14.261241+00
resolve_citation:s2	ref	untyped	ref_artifacts	Semantic Scholar metadata enrichment for stub refs	\N	2026-05-30 21:33:14.261241+00
keybert:chunks	chunk	typed	chunks	KeyBERT phrases per chunk; abbrev-aware via refs.meta[abbrevs]	\N	2026-06-05 06:56:11.586964+00
embed:tags	tag	typed	tag_embeddings	bge-m3 embeddings of every tag in use, for semantic discovery	\N	2026-06-05 16:35:39.082596+00
\.


--
-- Data for Name: chunk_kinds; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.chunk_kinds (slug, is_card, description, deprecated_at, created_at) FROM stdin;
card_combined	t	Title + authors + abstract + keywords + cite_key	\N	2026-05-21 20:06:05.179981+00
card_title	t	Title only	\N	2026-05-21 20:06:05.179981+00
card_authors	t	Normalised author list	\N	2026-05-21 20:06:05.179981+00
card_abstract	t	Abstract only	\N	2026-05-21 20:06:05.179981+00
card_meta	t	DOI / journal / year / venue	\N	2026-05-21 20:06:05.179981+00
card_keywords	t	RAKE keywords (scispacy-lemmatised, top-50)	\N	2026-05-21 20:06:05.179981+00
paragraph	f	Body paragraph	\N	2026-05-21 20:06:05.179981+00
figure	f	Figure caption + reference	\N	2026-05-21 20:06:05.179981+00
equation	f	Inline or display equation	\N	2026-05-21 20:06:05.179981+00
caption	f	Table / figure caption	\N	2026-05-21 20:06:05.179981+00
heading	f	Section heading (rarely standalone)	\N	2026-05-21 20:06:05.179981+00
references	f	Bibliography section (excluded from default embedding)	\N	2026-05-21 20:06:05.179981+00
code_symbol	f	Function / class / module body	\N	2026-05-21 20:06:05.179981+00
memory_body	f	Memory body text	\N	2026-05-21 20:06:05.179981+00
gripe_body	f	Gripe body text	\N	2026-05-21 20:06:05.179981+00
todo_body	f	Todo body text	\N	2026-05-21 20:06:05.179981+00
quest_body	f	Quest body text	\N	2026-05-21 20:06:05.179981+00
fc_claim	f	Flashcard claim side	\N	2026-05-21 20:06:05.179981+00
fc_evidence	f	Flashcard evidence side	\N	2026-05-21 20:06:05.179981+00
conv_message	f	Single message in a conversation	\N	2026-05-21 20:06:05.179981+00
qa_pair	f	Question + answer pair	\N	2026-05-21 20:06:05.179981+00
skill_overview	f	Skill overview section	\N	2026-05-21 20:06:05.179981+00
skill_input	f	Skill input description	\N	2026-05-21 20:06:05.179981+00
skill_output	f	Skill output description	\N	2026-05-21 20:06:05.179981+00
skill_example	f	Skill example	\N	2026-05-21 20:06:05.179981+00
tool_overview	f	Tool overview section	\N	2026-05-21 20:06:05.179981+00
tool_input_schema	f	Tool input schema	\N	2026-05-21 20:06:05.179981+00
tool_output_schema	f	Tool output schema	\N	2026-05-21 20:06:05.179981+00
tool_example	f	Tool example	\N	2026-05-21 20:06:05.179981+00
web_paragraph	f	Paragraph from a cached web result	\N	2026-05-21 20:06:05.179981+00
web_section	f	Section from a cached web result	\N	2026-05-21 20:06:05.179981+00
web_citation	f	Citation from a cached web result	\N	2026-05-21 20:06:05.179981+00
youtube_segment	f	YouTube transcript segment	\N	2026-05-21 20:06:05.179981+00
wolfram_query	f	Wolfram query text	\N	2026-05-21 20:06:05.179981+00
wolfram_response	f	Wolfram response text	\N	2026-05-21 20:06:05.179981+00
decision_section	f	Section of a decision log entry	\N	2026-05-21 20:06:05.179981+00
design_section	f	Section of a design document	\N	2026-05-21 20:06:05.179981+00
patent_claim	f	Individual patent claim	\N	2026-05-21 20:06:05.179981+00
patent_section	f	Patent section (description / drawings)	\N	2026-05-21 20:06:05.179981+00
project_goal	f	Project goal entry	\N	2026-05-21 20:06:05.179981+00
project_constraint	f	Project constraint entry	\N	2026-05-21 20:06:05.179981+00
project_decision_log	f	Project decision-log entry	\N	2026-05-21 20:06:05.179981+00
project_status	f	Project status entry	\N	2026-05-21 20:06:05.179981+00
project_open_question	f	Project open question	\N	2026-05-21 20:06:05.179981+00
project_milestone	f	Project milestone	\N	2026-05-21 20:06:05.179981+00
meeting_segment	f	Meeting transcript segment	\N	2026-05-21 20:06:05.179981+00
action_item	f	Action item from a meeting	\N	2026-05-21 20:06:05.179981+00
meeting_decision	f	Decision recorded in a meeting	\N	2026-05-21 20:06:05.179981+00
email_message	f	Email message body	\N	2026-05-21 20:06:05.179981+00
email_attachment_ref	f	Reference to an email attachment	\N	2026-05-21 20:06:05.179981+00
readme_section	f	README section	\N	2026-05-21 20:06:05.179981+00
commit_message	f	Commit message	\N	2026-05-21 20:06:05.179981+00
issue_comment	f	Comment on an issue	\N	2026-05-21 20:06:05.179981+00
issue_label_change	f	Label change on an issue	\N	2026-05-21 20:06:05.179981+00
issue_milestone	f	Milestone change on an issue	\N	2026-05-21 20:06:05.179981+00
research_report_summary	f	Research-report summary section	\N	2026-05-21 20:06:05.179981+00
research_report_citation	f	Research-report citation entry	\N	2026-05-21 20:06:05.179981+00
finding_body	f	Finding claim text (the measured value plus its bare conditions)	\N	2026-05-30 21:33:14.261241+00
finding_context	f	Finding setup envelope (instrument, electrode, ambient, technique, geometry)	\N	2026-05-30 21:33:14.261241+00
table	f	Markdown table emitted by Marker (skip RAKE).	\N	2026-06-04 19:55:50.15863+00
\.


--
-- Data for Name: embedders; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.embedders (name, dim, is_default, description, deprecated_at, created_at) FROM stdin;
bge-m3	1024	t	BAAI/bge-m3, dense; 1024-dim; multilingual	\N	2026-05-21 20:06:05.179981+00
\.


--
-- Data for Name: kinds; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.kinds (slug, is_numeric, title, description, deprecated_at, created_at) FROM stdin;
paper	f	Paper	Research paper, addressed by cite_key	\N	2026-05-21 20:06:05.179981+00
book	f	Book	Book or monograph	\N	2026-05-21 20:06:05.179981+00
patent	f	Patent	Patent document	\N	2026-05-21 20:06:05.179981+00
research_report	f	Research report	Research / industry report	\N	2026-05-21 20:06:05.179981+00
oracle	f	Oracle	Oracle / authority node	\N	2026-05-21 20:06:05.179981+00
skill	f	Skill	Agent skill document	\N	2026-05-21 20:06:05.179981+00
tool	f	Tool	Tool spec or interface description	\N	2026-05-21 20:06:05.179981+00
code	f	Code symbol	Function, class, module, or repo symbol	\N	2026-05-21 20:06:05.179981+00
decision	f	Decision	ADR-style decision log entry	\N	2026-05-21 20:06:05.179981+00
design	f	Design	Design document / plan	\N	2026-05-21 20:06:05.179981+00
project	f	Project	Project descriptor (goals, status, …)	\N	2026-05-21 20:06:05.179981+00
conv	f	Conversation	Conversation transcript	\N	2026-05-21 20:06:05.179981+00
meeting	f	Meeting	Meeting notes / transcript	\N	2026-05-21 20:06:05.179981+00
email	f	Email	Email message or thread	\N	2026-05-21 20:06:05.179981+00
repo	f	Repo	Source-code repository	\N	2026-05-21 20:06:05.179981+00
issue	f	Issue	Issue tracker item	\N	2026-05-21 20:06:05.179981+00
quest	f	Quest	Request queue item	\N	2026-05-21 20:06:05.179981+00
todo	t	Todo	Task / action item	\N	2026-05-21 20:06:05.179981+00
memory	t	Memory	Note, decision, idea, claim	\N	2026-05-21 20:06:05.179981+00
gripe	t	Gripe	Informal log entry	\N	2026-05-21 20:06:05.179981+00
fc	t	Flashcard	Spaced-repetition flashcard	\N	2026-05-21 20:06:05.179981+00
web	f	Web query	Cached web / research / think query	\N	2026-05-21 20:06:05.179981+00
youtube	f	YouTube	Cached YouTube transcript	\N	2026-05-21 20:06:05.179981+00
math	f	Math result	Cached Wolfram math result	\N	2026-05-21 20:06:05.179981+00
finding	t	Finding	A retrievable empirical claim with explicit setup context and a provenance chain back to its primary source. Synthesised by the citation-chase worker; never externally citable (see docs/design/finding-chase.md).	\N	2026-05-30 21:33:14.261241+00
citation	t	Citation	Verified claim → source pointer. Written by the citation-fill workflow after the verifier confirms the source quote supports the claim.	\N	2026-05-31 14:47:51.530091+00
markdown	f	Markdown file	Read / write .md / .markdown files under a configured root. Slug derived from path; lazy re-ingest on stale mtime; block slugs are content-stable. See src/precis/handlers/markdown.py.	\N	2026-06-04 19:55:50.290874+00
plaintext	f	Plaintext file	Read / write .txt / .org / .rst files under a configured root. The shared file-kind base; markdown and tex are subclasses. See src/precis/handlers/plaintext.py.	\N	2026-06-04 19:55:50.290874+00
tex	f	LaTeX file	Read / write .tex files under a configured root. Inherits the plaintext file-kind machinery; adds tex-aware block parsing + input-resolution. See src/precis/handlers/tex.py.	\N	2026-06-04 19:55:50.290874+00
websearch	f	Web search	Cached perplexity-style web search response. Slug derived from the canonical query + model + freshness window. See src/precis/handlers/perplexity.py.	\N	2026-06-04 20:01:59.625687+00
think	f	Think	Cached perplexity ``think`` (chain-of-thought) response. Slug derived from the question + model + freshness window. See src/precis/handlers/perplexity.py.	\N	2026-06-04 20:01:59.625687+00
research	f	Research report	Cached perplexity ``research`` (deep-research) response. Slug derived from the prompt + model + freshness window. See src/precis/handlers/perplexity.py.	\N	2026-06-04 20:01:59.625687+00
\.


--
-- Data for Name: providers; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.providers (slug, description, deprecated_at, created_at) FROM stdin;
arxiv	arXiv preprint server	\N	2026-05-21 20:06:05.179981+00
crossref	Crossref DOI metadata	\N	2026-05-21 20:06:05.179981+00
s2	Semantic Scholar	\N	2026-05-21 20:06:05.179981+00
pubmed	PubMed / NCBI	\N	2026-05-21 20:06:05.179981+00
openalex	OpenAlex	\N	2026-05-21 20:06:05.179981+00
unpaywall	Unpaywall OA index	\N	2026-05-21 20:06:05.179981+00
perplexity	Perplexity (web / research / think)	\N	2026-05-21 20:06:05.179981+00
wolfram	Wolfram Alpha math	\N	2026-05-21 20:06:05.179981+00
youtube	YouTube transcript	\N	2026-05-21 20:06:05.179981+00
manual	Manually uploaded	\N	2026-05-21 20:06:05.179981+00
local	Local computation / no external source	\N	2026-05-21 20:06:05.179981+00
retraction_watch	Retraction Watch dataset (CC-BY via Crossref)	\N	2026-05-30 16:07:11.520836+00
web	Direct web fetch / trafilatura extraction	\N	2026-05-31 18:20:12.906601+00
epo_ops	European Patent Office Open Patent Services REST API	\N	2026-06-04 20:02:44.133862+00
\.


--
-- Data for Name: relations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.relations (slug, is_symmetric, inverse_slug, description, deprecated_at, created_at) FROM stdin;
related-to	t	\N	Symmetric association	\N	2026-05-21 20:06:05.179981+00
blocks	f	blocked-by	Source blocks target	\N	2026-05-21 20:06:05.179981+00
blocked-by	f	blocks	Source is blocked by target	\N	2026-05-21 20:06:05.179981+00
contradicts	f	contradicted-by	Source contradicts target	\N	2026-05-21 20:06:05.179981+00
contradicted-by	f	contradicts	Source is contradicted by target	\N	2026-05-21 20:06:05.179981+00
cites	f	cited-by	Source cites target	\N	2026-05-21 20:06:05.179981+00
cited-by	f	cites	Source is cited by target	\N	2026-05-21 20:06:05.179981+00
supersedes	f	superseded-by	Source supersedes target	\N	2026-05-21 20:06:05.179981+00
superseded-by	f	supersedes	Source is superseded by target	\N	2026-05-21 20:06:05.179981+00
retracted-by	f	retracts	Source is retracted by target (retraction notice)	\N	2026-05-30 16:07:11.520836+00
retracts	f	retracted-by	Source retracts target	\N	2026-05-30 16:07:11.520836+00
corrected-by	f	corrects	Source is corrected by target (corrigendum/erratum/addendum)	\N	2026-05-30 16:07:11.520836+00
corrects	f	corrected-by	Source corrects target	\N	2026-05-30 16:07:11.520836+00
concern-raised-by	f	raises-concern-about	Source has an Expression of Concern attached	\N	2026-05-30 16:07:11.520836+00
raises-concern-about	f	concern-raised-by	Source raises concern about target	\N	2026-05-30 16:07:11.520836+00
misattributes	f	misattributed-by	Source chunk misrepresents what the target chunk actually says	\N	2026-05-30 21:33:14.261241+00
misattributed-by	f	misattributes	Source chunk is misrepresented by the linked source chunk	\N	2026-05-30 21:33:14.261241+00
derived-from	f	derived-into	Source is derived from target (cause/origin)	\N	2026-05-31 18:20:12.906601+00
derived-into	f	derived-from	Source is the origin from which target derives	\N	2026-05-31 18:20:12.906601+00
supports	f	supported-by	Source provides evidence for target	\N	2026-05-31 18:20:12.906601+00
supported-by	f	supports	Source is supported by target	\N	2026-05-31 18:20:12.906601+00
generalises	f	specialises	Source is a generalisation of target	\N	2026-05-31 18:20:12.906601+00
specialises	f	generalises	Source is a specialisation of target	\N	2026-05-31 18:20:12.906601+00
see-also	f	\N	One-way "for context" pointer (no inverse)	\N	2026-05-31 18:20:12.906601+00
\.


--
-- Data for Name: summarizers; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.summarizers (name, prompt_template, config, is_default, description, deprecated_at, created_at) FROM stdin;
rake-lemma	\N	{"model": "en_core_sci_sm", "lemmatizer": "scispacy", "max_keywords": 50, "max_phrase_words": 4, "min_phrase_words": 1}	t	RAKE phrase extraction + scispacy lemmatisation	\N	2026-05-21 20:06:05.179981+00
\.


--
--

\unrestrict ydN3OtexeAo5wgMMm4wlYYswxG1X3mJPqoFdhMRle7WFa87pq9skqXcqrIauHFu

