-- 0009_ref_events.sql
--
-- Restore the `ref_events` table that 0001_initial.sql declares
-- but that drifted out of prod at some point — a fresh greenfield
-- deploy was missing it, which crashed every worker pass that
-- writes to the cross-subsystem audit trail
-- (`precis.store._events_ops`). Symptom on prod 2026-06-07:
-- `psycopg.errors.UndefinedTable: relation "ref_events" does not exist`
-- in /var/log/precis-worker.log on all cluster nodes. Backfilling
-- the table forward so any future provision step recreates it.
--
-- Additive only; forward-only (ADR 0005). Every statement is
-- idempotent so a re-run after a partial apply is safe.
--
-- Schema copied verbatim from the original definition in
-- 0001_initial.sql (lines 411–442, 714–717, 911–915, 1165–1175,
-- 1430–1434). If you change ref_events, ship the next forward
-- migration — do NOT edit this file.

BEGIN;

CREATE TABLE IF NOT EXISTS public.ref_events (
    event_id    bigint                   NOT NULL,
    ref_id      bigint                   NOT NULL,
    ts          timestamp with time zone DEFAULT now() NOT NULL,
    source      text                     NOT NULL,
    event       text                     NOT NULL,
    payload     jsonb,
    duration_ms integer,
    cost_usd    numeric
);

CREATE SEQUENCE IF NOT EXISTS public.ref_events_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.ref_events_event_id_seq
    OWNED BY public.ref_events.event_id;

ALTER TABLE ONLY public.ref_events
    ALTER COLUMN event_id SET DEFAULT nextval('public.ref_events_event_id_seq'::regclass);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname  = 'ref_events_pkey'
           AND conrelid = 'public.ref_events'::regclass
    ) THEN
        ALTER TABLE ONLY public.ref_events
            ADD CONSTRAINT ref_events_pkey PRIMARY KEY (event_id);
    END IF;
END$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname  = 'ref_events_ref_id_fkey'
           AND conrelid = 'public.ref_events'::regclass
    ) THEN
        ALTER TABLE ONLY public.ref_events
            ADD CONSTRAINT ref_events_ref_id_fkey
            FOREIGN KEY (ref_id) REFERENCES public.refs(ref_id) ON DELETE CASCADE;
    END IF;
END$$;

CREATE INDEX IF NOT EXISTS ref_events_ref_id_ts_idx
    ON public.ref_events USING btree (ref_id, ts DESC);

CREATE INDEX IF NOT EXISTS ref_events_source_event_ts_idx
    ON public.ref_events USING btree (source, event, ts DESC);

COMMIT;
