-- 0131_web_users.sql
--
-- Authenticated humans for the precis-web HTTP surface. Until now the tab
-- UI — /secrets, /env, /console and every mutation route — was reachable by
-- anything on the tailnet; `WebConfig` said so in its own docstring ("no auth
-- in cut 1") and its `auth_token` field was never read by anything.
--
-- Every row here is FULLY AUTHORIZED: there is no role column and no
-- per-route ACL. Fine-grained multi-user is a separate, deferred design
-- (docs/backlog/user-identity-and-ask-routing.md); this table exists so the
-- door has a lock, not so the rooms have different keys.
--
-- Password storage: per-user 16-byte salt + scrypt (stdlib, memory-hard —
-- the repo carries no bcrypt/argon2/passlib), with the plaintext HMAC'd
-- under a vault-resident pepper first. `password_algo` records which of the
-- two ('scrypt-v1' / 'scrypt-pepper-v1') produced the row so the KDF can
-- migrate per user instead of by flag-day. The pepper matters because
-- `precis.secrets` promises a *logical* pg_dump is safe to share — a plain
-- salted hash here would quietly put crackable credentials into that dump.
--
-- `abbrev` is carried now and displayed later: the eventual "who edited
-- this" affordance wants a 2-4 char handle it can render inline and link to
-- a user page. Kept distinct from `login` on purpose — a credential and a
-- display token should be independently changeable.
--
-- `feed_token_sha256` is the podcast escape hatch: phone podcast clients
-- handle HTTP Basic inconsistently on enclosure URLs, so /podcast also
-- accepts ?t=<token>. Stored as a bare SHA-256 (no KDF): the token is 32
-- random bytes, so there is nothing to brute-force.
--
-- login/abbrev/email are stored lowercased (CHECK-enforced) so uniqueness is
-- case-insensitive without depending on the citext extension.
--
-- Forward-only (ADR 0005). Idempotent.

CREATE TABLE IF NOT EXISTS web_users (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login             text NOT NULL UNIQUE CHECK (login = lower(login) AND login <> ''),
    abbrev            text NOT NULL UNIQUE CHECK (abbrev = lower(abbrev) AND abbrev <> ''),
    full_name         text,
    email             text CHECK (email IS NULL OR email = lower(email)),
    password_hash     text NOT NULL,
    password_salt     text NOT NULL,
    password_algo     text NOT NULL,
    feed_token_sha256 text UNIQUE,
    disabled_at       timestamptz,
    last_login_at     timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE web_users IS
    'Fully-authorized humans for the precis-web Basic-auth gate. No roles.';
COMMENT ON COLUMN web_users.abbrev IS
    'Short display handle for per-user edit attribution (rendered + linked later).';
COMMENT ON COLUMN web_users.password_algo IS
    'scrypt-v1 | scrypt-pepper-v1 — which KDF/pepper produced password_hash.';
COMMENT ON COLUMN web_users.feed_token_sha256 IS
    'SHA-256 of the per-user ?t= podcast credential. NULL = no feed token minted.';
