-- 0168_paper_authors.sql
--
-- First-normal-form byline: one ``paper_authors`` row per (paper,
-- position). ``refs.authors`` (jsonb) is a repeating group in two shapes
-- (``{name}`` legacy / ``{given, family}`` canonical) with no convention
-- inside the ``{name}`` strings, which made author search a jsonb
-- expression over one key and left ``{given, family}`` papers invisible
-- to it. The table is the source of truth from here on; ``refs.authors``
-- stays as a *projection* regenerated by the single writer
-- (``store.set_paper_authors``) so the existing readers keep working.
--
-- Columns:
--   given / middle / family   the split name; ``middle`` is a real column
--                             (NOT NULL, '' when unknown) derived at write
--                             time from the trailing initials of ``given``
--                             (``utils/authors.py::split_middle``) — no
--                             registry delivers it separately.
--   name_raw                  the string as received, never rewritten —
--                             the audit trail for the splitter.
--   orcid                     dashed iD (tier-1 identity).
--   openalex_author_id        OpenAlex ``A…`` id — the fallback identity
--                             for authors without an ORCID.
--   person_ref_id             the ``kind='orcid'`` node when one exists.
--   source                    which tier wrote the row.
--   verified_at               ORCID cross-check (paper DOI in the
--                             person's works) or a human edit.
--
-- The data backfill below projects every existing byline in SQL so
-- search never goes dark between migrate and the Python
-- ``precis paper authors-resplit`` pass (which applies the middle-initial
-- split + the junk guard the SQL projection can't). ``{name}`` entries
-- split on a single comma ("Family, Given") — the only unambiguous
-- flat form; everything else keeps the name in ``name_raw`` with empty
-- name columns. ``source='legacy'`` marks every projected row so the
-- enrichment tiers replace them freely.
--
-- ``cite_key`` is deliberately untouched by anything here or by the
-- writer: it is a stored identifier coupled to the corpus PDF path.
--
-- Forward-only (ADR 0005). Idempotent (``IF NOT EXISTS``; the backfill
-- inserts only for papers with no rows yet).

BEGIN;

CREATE TABLE IF NOT EXISTS paper_authors (
    ref_id              bigint      NOT NULL REFERENCES refs (ref_id) ON DELETE CASCADE,
    position            smallint    NOT NULL,
    given               text        NOT NULL DEFAULT '',
    middle              text        NOT NULL DEFAULT '',
    family              text        NOT NULL DEFAULT '',
    name_raw            text        NOT NULL,
    orcid               text,
    openalex_author_id  text,
    person_ref_id       bigint      REFERENCES refs (ref_id) ON DELETE SET NULL,
    source              text        NOT NULL,
    verified_at         timestamptz,
    updated_at          timestamptz NOT NULL DEFAULT now(),
    -- Display form "Given M. Family" with empty parts collapsed (no
    -- double space when middle = ''); the search expression and its
    -- trigram index both read this column.
    full_name           text GENERATED ALWAYS AS (
        btrim(regexp_replace(given || ' ' || middle || ' ' || family, ' +', ' ', 'g'))
    ) STORED,
    PRIMARY KEY (ref_id, position),
    CONSTRAINT paper_authors_position_positive CHECK (position >= 1),
    CONSTRAINT paper_authors_source_check CHECK (
        source IN ('orcid', 'crossref', 'openalex', 's2', 'pdf', 'legacy', 'llm', 'human')
    ),
    CONSTRAINT paper_authors_some_name CHECK (
        given <> '' OR family <> '' OR name_raw <> ''
    ),
    CONSTRAINT paper_authors_orcid_format CHECK (
        orcid IS NULL OR orcid ~ '^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]$'
    )
);

COMMENT ON TABLE paper_authors IS
    'One row per (paper, byline position). Source of truth for a paper''s '
    'authors; refs.authors is the jsonb projection regenerated by '
    'store.set_paper_authors. source = tier that wrote the row; '
    'verified_at = ORCID cross-check or human edit.';

CREATE INDEX IF NOT EXISTS paper_authors_family_lc_idx
    ON paper_authors (lower(family));
CREATE INDEX IF NOT EXISTS paper_authors_fullname_trgm_idx
    ON paper_authors USING gin (full_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS paper_authors_orcid_idx
    ON paper_authors (orcid) WHERE orcid IS NOT NULL;
CREATE INDEX IF NOT EXISTS paper_authors_openalex_idx
    ON paper_authors (openalex_author_id) WHERE openalex_author_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS paper_authors_person_idx
    ON paper_authors (person_ref_id) WHERE person_ref_id IS NOT NULL;

-- Project existing bylines. Each jsonb element becomes one row; the
-- semicolon-packed-string shape (authors not an array) and anything the
-- SQL split can't handle is left to `precis paper authors-resplit`, which
-- also sweeps every paper with a non-empty jsonb and zero rows. The
-- element's display string is kept verbatim in name_raw.
INSERT INTO paper_authors
    (ref_id, position, given, middle, family, name_raw, orcid, person_ref_id, source)
SELECT
    r.ref_id,
    e.ord::smallint,
    -- given: canonical key wins; a single-comma {name} splits "Family, Given".
    CASE
        WHEN e.elem ? 'given' OR e.elem ? 'family' THEN coalesce(e.elem->>'given', '')
        WHEN (e.elem->>'name') LIKE '%,%'
             AND (e.elem->>'name') NOT LIKE '%,%,%'
            THEN btrim(split_part(e.elem->>'name', ',', 2))
        ELSE ''
    END,
    '',
    CASE
        WHEN e.elem ? 'given' OR e.elem ? 'family' THEN coalesce(e.elem->>'family', '')
        WHEN (e.elem->>'name') LIKE '%,%'
             AND (e.elem->>'name') NOT LIKE '%,%,%'
            THEN btrim(split_part(e.elem->>'name', ',', 1))
        ELSE ''
    END,
    coalesce(
        e.elem->>'name',
        btrim(concat_ws(' ', e.elem->>'given', e.elem->>'family')),
        ''
    ),
    -- orcid: strip a URL prefix, keep only a well-formed dashed iD.
    CASE
        WHEN regexp_replace(coalesce(e.elem->>'orcid', ''), '^.*orcid\.org/', '')
             ~ '^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]$'
            THEN regexp_replace(e.elem->>'orcid', '^.*orcid\.org/', '')
        ELSE NULL
    END,
    (SELECT ri.ref_id FROM ref_identifiers ri
      WHERE ri.id_kind = 'cite_key'
        AND ri.id_value = 'orcid:' || regexp_replace(coalesce(e.elem->>'orcid', ''), '^.*orcid\.org/', '')
      LIMIT 1),
    'legacy'
FROM refs r
CROSS JOIN LATERAL jsonb_array_elements(r.authors) WITH ORDINALITY AS raw(elem, ord)
-- A bare-string element (legacy writers) is the {name} shape.
CROSS JOIN LATERAL (
    SELECT CASE WHEN jsonb_typeof(raw.elem) = 'string'
                THEN jsonb_build_object('name', raw.elem #>> '{}')
                ELSE raw.elem END AS elem,
           raw.ord
) AS e
WHERE r.kind = 'paper'
  AND jsonb_typeof(r.authors) = 'array'
  AND jsonb_typeof(e.elem) = 'object'
  AND btrim(coalesce(e.elem->>'name', concat_ws(' ', e.elem->>'given', e.elem->>'family'), '')) <> ''
  AND NOT EXISTS (SELECT 1 FROM paper_authors pa WHERE pa.ref_id = r.ref_id)
ON CONFLICT (ref_id, position) DO NOTHING;

COMMIT;

-- End of 0168_paper_authors.sql
