"""scripts/lib/check-entry-points.py — preflight: installed entry-points match
the worktree's pyproject.toml.

`scripts/test` runs `uv run --no-sync` against the venv BAKED into the
precis-dev image (docker/Dockerfile `dev` stage: `uv pip install --no-deps -e
/app` at image-build time). The compose bind-mount makes the SOURCE tree live
(`import precis_se.handler` resolves to the host), but `importlib.metadata`
reads the STATIC `entry_points.txt` in the venv's dist-info — baked at build
time, never regenerated by the `--no-sync` run. So a container built before an
entry-points change keeps serving the old table no matter how current the
mounted `pyproject.toml` is (gr453828: an image baked before the nm->se merge
still reported `nm` registered and `se` absent, silently breaking any test that
reads the real `entry_points(group="precis.handlers")`).

This is the sibling of check-core-deps.py: same stale-baked-venv failure mode,
same "fail loud before pytest, name the drift + the fix" contract — but for the
`[project.entry-points.*]` tables rather than `[project] dependencies`. Unlike a
missing core dep, entry-point drift has no red ModuleNotFoundError to point at;
it hands wrong answers to `importlib.metadata.entry_points()` while every import
still succeeds, so it must be checked explicitly.

A UV_WITH bridge can't paper over this one (entry-points come from install-time
metadata, not from `--with`). `--heal` (what scripts/test passes) repairs it
for the one run instead: it re-runs the image's own editable install
(`uv pip install --python <this venv> --no-deps -e <root>`, ~3 s) inside the
throwaway `compose run --rm` container, which regenerates the dist-info, then
re-checks. That container is discarded, so the shared image stays untouched
and no sibling worktree is affected; a rebuild only stops the per-run cost.
This is what lets an entry-point change (plugin-split step 3, gr459123) land
without a coordinated rebuild of the shared precis-dev image. The ship gate
needs none of this: it runs `uv run` without `--no-sync`, which re-syncs the
project into /opt/venv on its own.
"""

from __future__ import annotations

import subprocess
import sys
import tomllib
from importlib.metadata import distribution
from pathlib import Path

PYPROJECT_PATH = Path(__file__).resolve().parents[2] / "pyproject.toml"


def _declared_groups(pyproject: dict) -> dict[str, dict[str, str]]:
    """The `[project.entry-points.*]` tables from pyproject.toml, as
    {group: {name: value}}. tomllib nests these under
    project.entry-points.<group>."""
    return dict(pyproject.get("project", {}).get("entry-points", {}))


def _installed_group(dist_name: str, group: str) -> dict[str, str]:
    """This project's installed dist-info entry-points for one group, as
    {name: value}. Scoped to our own dist: another package in the venv may
    register into a `precis.*` group, and that is not drift in this tree.
    Reads static metadata only — never `.load()` (the exact call that raised
    fleet-wide in gr451358; discovery must stay metadata-only)."""
    return {
        ep.name: ep.value
        for ep in distribution(dist_name).entry_points
        if ep.group == group
    }


def _drift(data: dict) -> list[str]:
    groups = _declared_groups(data)
    dist_name = data["project"]["name"]

    drift: list[str] = []
    for group, declared in groups.items():
        installed = _installed_group(dist_name, group)
        for name, value in declared.items():
            if name not in installed:
                drift.append(f"{group}: '{name}' declared but not installed")
            elif installed[name] != value:
                drift.append(
                    f"{group}: '{name}' installed as {installed[name]!r}, "
                    f"pyproject declares {value!r}"
                )
        for name in installed:
            if name not in declared:
                drift.append(f"{group}: '{name}' installed but no longer declared")
    return drift


def _reinstall() -> bool:
    """Redo the image's editable install into the running venv, so its
    dist-info (and entry_points.txt) match the mounted pyproject."""
    cmd = [
        "uv", "pip", "install", "--python", sys.executable,
        "--no-deps", "-e", str(PYPROJECT_PATH.parent), "-q",
    ]  # fmt: skip
    return subprocess.run(cmd, check=False).returncode == 0


def main(argv: list[str]) -> int:
    data = tomllib.loads(PYPROJECT_PATH.read_text(encoding="utf-8"))
    drift = _drift(data)
    if drift and "--heal" in argv:
        print(
            "precis-dev image predates this tree's entry-points ("
            + "; ".join(drift)
            + ") — reinstalling into this run's container only; "
            "scripts/build-image precis-dev stops the per-run cost.",
            file=sys.stderr,
        )
        if _reinstall():
            drift = _drift(data)

    if drift:
        print(
            "stale precis-dev image — installed entry-points don't match "
            "this worktree's pyproject.toml:\n  " + "\n  ".join(drift) + "\n"
            "fix: run scripts/build-image precis-dev (entry-points come from "
            "install-time dist-info metadata, not the bind-mounted source, so "
            "an image rebuild is the only fix — UV_WITH can't bridge this).",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
