"""FastAPI application factory.

``create_app`` wires the four tab routers, the error handlers, the HTTP
Basic gate (:mod:`precis_web.auth`, on unless ``PRECIS_WEB_AUTH`` says
otherwise), and a lifespan that builds the single
:class:`precis.runtime.PrecisRuntime` at startup (and closes its store
at shutdown). Tests pass a pre-built (possibly fake) runtime to skip the
DB connect.
"""

from __future__ import annotations

import logging
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

from fastapi import FastAPI
from fastapi.responses import RedirectResponse
from fastapi.staticfiles import StaticFiles

from precis_web.config import WebConfig
from precis_web.errors import register_error_handlers

log = logging.getLogger(__name__)


def create_app(
    *,
    runtime: Any | None = None,
    web_config: WebConfig | None = None,
) -> FastAPI:
    """Build the precis-web FastAPI app.

    ``runtime`` — inject a pre-built runtime (tests, or an embedding
    caller that already holds one). When ``None``, the lifespan builds
    one from the environment at startup and closes it at shutdown.
    ``web_config`` — defaults to :meth:`WebConfig.from_env`.
    """
    cfg = web_config or WebConfig.from_env()

    @asynccontextmanager
    async def lifespan(app: FastAPI):
        owns_runtime = False
        if getattr(app.state, "runtime", None) is None:
            from precis.runtime import build_runtime

            log.info("precis web: building runtime")
            app.state.runtime = build_runtime()
            owns_runtime = True
        try:
            yield
        finally:
            if owns_runtime:
                store = getattr(app.state.runtime, "store", None)
                if store is not None:
                    store.close()

    app = FastAPI(title="precis web", lifespan=lifespan)
    app.state.web_config = cfg
    if runtime is not None:
        app.state.runtime = runtime

    # Gzip every response the client accepts (Starlette negotiates + sets
    # Vary: Accept-Encoding). The reader HTML is highly repetitive — a
    # 10k-block draft's ~2 MB page compresses ~10× on the wire — and uvicorn
    # serves it raw with no proxy in front, so this is the single biggest
    # transfer win and it applies to every page. minimum_size skips tiny bodies
    # where the gzip header would cost more than it saves.
    from starlette.middleware.gzip import GZipMiddleware

    app.add_middleware(GZipMiddleware, minimum_size=1024)

    # HTTP Basic in front of everything — routes, the /static mount, and
    # anything added later. Added AFTER gzip so it is the OUTERMOST layer
    # (Starlette applies middleware in reverse): an unauthenticated
    # request is rejected before any handler or compressor touches it.
    # Off only when PRECIS_WEB_AUTH explicitly says so; see
    # WebConfig.auth_required for why the dataclass default differs from
    # the from_env default.
    if cfg.auth_required:
        from precis_web.auth import BasicAuthMiddleware

        app.add_middleware(BasicAuthMiddleware)
    else:
        log.warning(
            "precis web: HTTP auth DISABLED (PRECIS_WEB_AUTH) — every route, "
            "including /secrets and /console, is open to anything that can "
            "reach this port"
        )

    # Hardening headers LAST, so this is the outermost layer and they ride
    # on the 401 challenge and /static too, not just handler responses.
    # Unconditional: framing and MIME-sniffing don't care whether auth is
    # on, and the auth-off path is exactly when the app is most exposed.
    from precis_web.security_headers import SecurityHeadersMiddleware

    app.add_middleware(SecurityHeadersMiddleware)

    register_error_handlers(app)

    # Self-hosted front-end assets under static/ (tailwind.css — a prebuilt
    # static stylesheet regenerated by scripts/ship, replacing the Play CDN;
    # prosemirror.bundle.mjs; vendored pdf.js), so there is no external CDN
    # dependency at runtime.
    static_dir = Path(__file__).parent / "static"
    static_dir.mkdir(exist_ok=True)
    app.mount("/static", StaticFiles(directory=static_dir), name="static")

    # Routers — one per tab. Imported here (not at module top) so the
    # package import surface stays light and circular-import-free.
    from precis_web.routes import (
        account,
        agentlogs,
        alerts,
        asks,
        budget,
        cad,
        categorizers,
        cfp,
        claim,
        clusters,
        console,
        datasheets,
        drafts,
        drive,
        env,
        factory,
        figure,
        flags,
        gripes,
        items,
        llm,
        manual,
        mermaid,
        nanopub,
        needs_you,
        papers,
        papers_needed,
        pcb,
        podcast,
        pres,
        preview,
        refs,
        secrets,
        settings,
        smartdraft,
        status,
        structure,
        tags,
        todo,
    )

    app.include_router(todo.router)
    app.include_router(needs_you.router)
    app.include_router(asks.router)
    app.include_router(papers.router)
    app.include_router(cfp.router)
    app.include_router(pres.router)
    app.include_router(datasheets.router)
    app.include_router(papers_needed.router)
    app.include_router(podcast.router)
    app.include_router(flags.router)
    app.include_router(items.router)
    app.include_router(llm.router)
    app.include_router(drafts.router)
    app.include_router(smartdraft.router)
    app.include_router(drive.router)
    app.include_router(drive.downloads_router)
    app.include_router(refs.router)
    app.include_router(tags.router)
    app.include_router(clusters.router)
    app.include_router(structure.router)
    app.include_router(cad.router)
    app.include_router(categorizers.router)
    app.include_router(figure.router)
    app.include_router(mermaid.router)
    app.include_router(pcb.router)
    app.include_router(nanopub.router)
    app.include_router(alerts.router)
    app.include_router(gripes.router)
    app.include_router(agentlogs.router)
    app.include_router(claim.router)
    app.include_router(preview.router)
    app.include_router(console.router)
    app.include_router(status.router)
    app.include_router(budget.router)
    app.include_router(env.router)
    app.include_router(factory.router)
    app.include_router(secrets.router)
    app.include_router(settings.router)
    app.include_router(manual.router)
    app.include_router(account.router)

    @app.get("/", include_in_schema=False)
    async def _root() -> RedirectResponse:
        return RedirectResponse(url="/drive")

    @app.get("/healthz", include_in_schema=False)
    async def _healthz() -> dict[str, str]:
        return {"status": "ok"}

    return app
