#!/usr/bin/env python3
"""PreToolUse hook: block edits to a SEALED (already-shipped) migration.

The footgun this closes: migrations are **forward-only** (ADR 0005). Editing a
``*.sql`` that already shipped to ``main`` changes its checksum → the migration
ledger mismatches on the next run against the shared ``precis_test`` DB (and
worse, silently diverges prod from the file). The fix for a migration bug is a
NEW forward migration, never an in-place edit. The baseline snapshot
(``migrations/baseline/schema.sql``) is regenerated by ``scripts/bump`` /
``precis db dump-schema``, never hand-edited.

Denied: Edit/Write to a numbered ``…/migrations/NNNN_*.sql`` that exists on
``origin/main``, or to ``…/migrations/baseline/*``.
Allowed: a brand-new migration file (not yet on ``origin/main``) — you're still
authoring it — and everything else.

Escape hatch: ``ALLOW_SEALED_MIGRATION_EDIT=1`` (e.g. the rare ledger-repair).

Wired in ``.claude/settings.json`` (PreToolUse, matcher
``Edit|Write|MultiEdit|NotebookEdit``). Mirrors ``guard-worktree-path.py``.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys

_NUMBERED = re.compile(r"/migrations/[0-9]{4}_[^/]+\.sql$")
_BASELINE = re.compile(r"/migrations/baseline/")


def _sealed(path: str) -> bool:
    """True if ``path`` already exists on ``origin/main`` (shipped → sealed)."""
    try:
        top = subprocess.run(
            ["git", "-C", os.path.dirname(path) or ".", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        rel = os.path.relpath(path, top)
        # exists on origin/main? (the shipped tree). Missing ref → not sealed.
        r = subprocess.run(
            ["git", "-C", top, "cat-file", "-e", f"origin/main:{rel}"],
            capture_output=True,
        )
        return r.returncode == 0
    except Exception:
        return False  # can't tell → don't block


def evaluate(path: str) -> str | None:
    """Return a deny reason, or ``None`` to allow. Pure-ish (shells to git)."""
    if not isinstance(path, str) or "/migrations/" not in path.replace("\\", "/"):
        return None
    p = path.replace("\\", "/")
    if _BASELINE.search(p):
        return (
            f"Refusing to edit the baseline snapshot ({os.path.basename(path)}). "
            "It is generated (`scripts/bump` / `precis db dump-schema`), never "
            "hand-edited (ADR 0031). Set ALLOW_SEALED_MIGRATION_EDIT=1 to override."
        )
    if _NUMBERED.search(p) and _sealed(path):
        return (
            f"Refusing to edit a SEALED migration ({os.path.basename(path)}) — it "
            "already shipped to origin/main. Migrations are forward-only (ADR 0005): "
            "editing it breaks the ledger checksum. Ship a NEW forward migration to "
            "fix it. Set ALLOW_SEALED_MIGRATION_EDIT=1 for a deliberate ledger repair."
        )
    return None


def main() -> int:
    if os.environ.get("ALLOW_SEALED_MIGRATION_EDIT"):
        return 0
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return 0
    path = (payload.get("tool_input") or {}).get("file_path", "")
    reason = evaluate(path)
    if reason is None:
        return 0
    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "deny",
                    "permissionDecisionReason": reason,
                }
            }
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
